// Generated by Trae Work
// YCC's Lab - Creative Developer Lab v3.0

document.addEventListener('DOMContentLoaded', function () {
  'use strict';

  // ==========================================
  // 1. 流星尾迹鼠标效果
  // ==========================================
  const trailCanvas = document.getElementById('trailCanvas');
  const trailCtx = trailCanvas.getContext('2d');
  let trailParticles = [];
  let mouseX = 0, mouseY = 0;
  let lastMouseX = 0, lastMouseY = 0;
  let mouseSpeed = 0;

  function resizeTrailCanvas() {
    trailCanvas.width = window.innerWidth;
    trailCanvas.height = window.innerHeight;
  }
  resizeTrailCanvas();
  window.addEventListener('resize', resizeTrailCanvas);

  document.addEventListener('mousemove', (e) => {
    lastMouseX = mouseX;
    lastMouseY = mouseY;
    mouseX = e.clientX;
    mouseY = e.clientY;

    // 计算鼠标速度
    const dx = mouseX - lastMouseX;
    const dy = mouseY - lastMouseY;
    mouseSpeed = Math.min(Math.sqrt(dx * dx + dy * dy), 30);

    // 根据速度生成粒子
    if (mouseSpeed > 2) {
      const count = Math.floor(mouseSpeed / 4) + 1;
      for (let i = 0; i < count; i++) {
        createTrailParticle(
          mouseX + (Math.random() - 0.5) * 10,
          mouseY + (Math.random() - 0.5) * 10
        );
      }
    }
  });

  function createTrailParticle(x, y) {
    const colors = [
      'rgba(139, 92, 246, ',
      'rgba(167, 139, 250, ',
      'rgba(6, 182, 212, ',
      'rgba(244, 114, 182, '
    ];
    trailParticles.push({
      x: x,
      y: y,
      vx: (Math.random() - 0.5) * 1.5,
      vy: (Math.random() - 0.5) * 1.5 - 0.5,
      radius: Math.random() * 3 + 1.5,
      life: 1,
      decay: Math.random() * 0.02 + 0.012,
      color: colors[Math.floor(Math.random() * colors.length)]
    });

    if (trailParticles.length > 200) {
      trailParticles.shift();
    }
  }

  function animateTrail() {
    trailCtx.clearRect(0, 0, trailCanvas.width, trailCanvas.height);

    // 绘制尾迹连线
    if (trailParticles.length > 1) {
      trailCtx.beginPath();
      trailCtx.moveTo(trailParticles[0].x, trailParticles[0].y);
      for (let i = 1; i < trailParticles.length; i++) {
        const p = trailParticles[i];
        if (p.life > 0.3) {
          trailCtx.lineTo(p.x, p.y);
        }
      }
      trailCtx.strokeStyle = 'rgba(139, 92, 246, 0.15)';
      trailCtx.lineWidth = 2;
      trailCtx.lineCap = 'round';
      trailCtx.lineJoin = 'round';
      trailCtx.stroke();
    }

    // 绘制粒子
    for (let i = trailParticles.length - 1; i >= 0; i--) {
      const p = trailParticles[i];
      p.x += p.vx;
      p.y += p.vy;
      p.vy += 0.02; // 轻微重力
      p.life -= p.decay;
      p.radius *= 0.98;

      if (p.life <= 0 || p.radius < 0.2) {
        trailParticles.splice(i, 1);
        continue;
      }

      // 发光粒子
      const gradient = trailCtx.createRadialGradient(p.x, p.y, 0, p.x, p.y, p.radius * 3);
      gradient.addColorStop(0, p.color + (p.life * 0.9) + ')');
      gradient.addColorStop(0.4, p.color + (p.life * 0.4) + ')');
      gradient.addColorStop(1, p.color + '0)');

      trailCtx.beginPath();
      trailCtx.arc(p.x, p.y, p.radius * 3, 0, Math.PI * 2);
      trailCtx.fillStyle = gradient;
      trailCtx.fill();

      // 核心亮点
      trailCtx.beginPath();
      trailCtx.arc(p.x, p.y, p.radius * 0.5, 0, Math.PI * 2);
      trailCtx.fillStyle = 'rgba(255, 255, 255, ' + (p.life * 0.8) + ')';
      trailCtx.fill();
    }

    requestAnimationFrame(animateTrail);
  }
  animateTrail();

  // ==========================================
  // 2. 网格翻砖滚动过渡（canvas）
  // ==========================================
  const gridCanvas = document.getElementById('gridCanvas');
  const gridCtx = gridCanvas.getContext('2d');
  const sectionList = document.querySelectorAll('.section');

  // 浅色主题各 section 的颜色
  const themeColors = [
    { bg: '#f8f9fc', grid: 'rgba(109, 40, 217, 0.07)', accent: '#8b5cf6' },   // Hero - 紫
    { bg: '#f5f9fb', grid: 'rgba(8, 145, 178, 0.07)', accent: '#06b6d4' },   // About - 青
    { bg: '#faf6fc', grid: 'rgba(219, 39, 119, 0.06)', accent: '#ec4899' },  // Skills - 粉
    { bg: '#f6f8fc', grid: 'rgba(37, 99, 235, 0.07)', accent: '#3b82f6' },  // Projects - 蓝
    { bg: '#fcf9f5', grid: 'rgba(217, 119, 6, 0.06)', accent: '#f59e0b' },  // Ideas - 橙
    { bg: '#f5faf7', grid: 'rgba(5, 150, 105, 0.06)', accent: '#10b981' },  // Notes - 绿
    { bg: '#f8f9fc', grid: 'rgba(109, 40, 217, 0.07)', accent: '#8b5cf6' }  // Contact - 紫
  ];

  const TILE_SIZE = 6; // 网格块大小（更细密）
  let gridCols = 0, gridRows = 0;
  let tiles = []; // 每个方块的状态
  let currentThemeIdx = 0;
  let nextThemeIdx = 0;

  // 给每个 section 注入光晕元素
  sectionList.forEach((section) => {
    const glow1 = document.createElement('div');
    glow1.className = 'section-glow glow-1';
    const glow2 = document.createElement('div');
    glow2.className = 'section-glow glow-2';
    section.insertBefore(glow1, section.firstChild);
    section.insertBefore(glow2, section.firstChild);
  });

  function resizeGridCanvas() {
    const dpr = window.devicePixelRatio || 1;
    gridCanvas.width = window.innerWidth * dpr;
    gridCanvas.height = window.innerHeight * dpr;
    gridCanvas.style.width = window.innerWidth + 'px';
    gridCanvas.style.height = window.innerHeight + 'px';
    gridCtx.scale(dpr, dpr);

    gridCols = Math.ceil(window.innerWidth / TILE_SIZE) + 2;
    gridRows = Math.ceil(window.innerHeight / TILE_SIZE) + 2;

    // 初始化所有方块
    tiles = [];
    for (let r = 0; r < gridRows; r++) {
      tiles[r] = [];
      for (let c = 0; c < gridCols; c++) {
        tiles[r][c] = {
          flipProgress: 0,  // 0 = 当前色, 1 = 新色
          flipping: false,
          delay: 0
        };
      }
    }
  }
  resizeGridCanvas();
  window.addEventListener('resize', resizeGridCanvas);

  // hex 转 rgba
  function hexToRgba(hex, alpha) {
    const r = parseInt(hex.slice(1, 3), 16);
    const g = parseInt(hex.slice(3, 5), 16);
    const b = parseInt(hex.slice(5, 7), 16);
    return `rgba(${r}, ${g}, ${b}, ${alpha})`;
  }

  // 颜色插值
  function lerpColor(color1, color2, t) {
    // 解析 rgba
    const parse = (c) => {
      const m = c.match(/rgba?\((\d+),\s*(\d+),\s*(\d+)(?:,\s*([\d.]+))?\)/);
      if (m) {
        return [parseInt(m[1]), parseInt(m[2]), parseInt(m[3]), parseFloat(m[4] || 1)];
      }
      return [0, 0, 0, 1];
    };
    const [r1, g1, b1, a1] = parse(color1);
    const [r2, g2, b2, a2] = parse(color2);
    const r = Math.round(r1 + (r2 - r1) * t);
    const g = Math.round(g1 + (g2 - g1) * t);
    const b = Math.round(b1 + (b2 - b1) * t);
    const a = (a1 + (a2 - a1) * t).toFixed(3);
    return `rgba(${r}, ${g}, ${b}, ${a})`;
  }

  // 计算两个 section 之间的滚动进度 (0-1)
  function getScrollProgress() {
    const scrollY = window.scrollY;
    const viewportH = window.innerHeight;

    // 找到当前跨越的边界
    for (let i = 0; i < sectionList.length - 1; i++) {
      const sectionBottom = sectionList[i].offsetTop + sectionList[i].offsetHeight;
      const nextSectionBottom = sectionList[i + 1].offsetTop + sectionList[i + 1].offsetHeight;

      // 当视窗中间在两个 section 之间时
      const midPoint = scrollY + viewportH * 0.5;
      const boundary = sectionList[i + 1].offsetTop;

      // 以边界为中心，前后各半屏作为过渡区域
      const transitionZone = viewportH * 0.8;
      const start = boundary - transitionZone * 0.5;
      const end = boundary + transitionZone * 0.5;

      if (midPoint >= start && midPoint <= end) {
        const progress = (midPoint - start) / (end - start);
        return {
          fromIdx: i,
          toIdx: i + 1,
          progress: Math.max(0, Math.min(1, progress))
        };
      }
    }

    // 不在过渡区域，返回当前所在 section
    let currentIdx = 0;
    const midPoint = scrollY + viewportH * 0.5;
    for (let i = 0; i < sectionList.length; i++) {
      const top = sectionList[i].offsetTop;
      const bottom = top + sectionList[i].offsetHeight;
      if (midPoint >= top && midPoint < bottom) {
        currentIdx = i;
        break;
      }
    }
    return { fromIdx: currentIdx, toIdx: currentIdx, progress: 0 };
  }

  // 触发翻砖动画
  let lastFromIdx = 0;
  let lastToIdx = 0;
  let lastProgress = 0;

  function updateGridFlip() {
    const { fromIdx, toIdx, progress } = getScrollProgress();

    // 如果跨越了新的边界，重置所有方块
    if (fromIdx !== lastFromIdx || toIdx !== lastToIdx) {
      lastFromIdx = fromIdx;
      lastToIdx = toIdx;

      // 如果是同一个 section，全部重置为 0
      if (fromIdx === toIdx) {
        for (let r = 0; r < gridRows; r++) {
          for (let c = 0; c < gridCols; c++) {
            tiles[r][c].flipProgress = 0;
            tiles[r][c].flipping = false;
          }
        }
        currentThemeIdx = fromIdx;
        nextThemeIdx = fromIdx;
        document.body.style.backgroundColor = themeColors[fromIdx].bg;
      } else {
         // 新的过渡开始，计算每块的延迟（从上到下波浪式）
         const dir = toIdx > fromIdx ? 1 : -1;
         for (let r = 0; r < gridRows; r++) {
           for (let c = 0; c < gridCols; c++) {
             // 从上往下按行分布延迟，每列加一点随机偏移
             const normalizedRow = dir > 0 ? r / gridRows : (gridRows - r) / gridRows;
             tiles[r][c].delay = normalizedRow * 0.5 + Math.random() * 0.12;
             tiles[r][c].flipping = false;
             // 如果往回滚，重置进度
             if (dir < 0 && tiles[r][c].flipProgress > 0.5) {
               tiles[r][c].flipProgress = 1 - tiles[r][c].flipProgress;
             }
           }
         }
         currentThemeIdx = fromIdx;
         nextThemeIdx = toIdx;
       }
    }

    lastProgress = progress;

    // 更新每块的翻转进度
    if (fromIdx !== toIdx) {
      for (let r = 0; r < gridRows; r++) {
        for (let c = 0; c < gridCols; c++) {
          const tile = tiles[r][c];
          const effectiveProgress = Math.max(0, Math.min(1, (progress - tile.delay) / 0.4));
          tile.flipProgress = effectiveProgress;
        }
      }

      // body 背景色在进度 50% 左右切换
      if (progress > 0.5) {
        document.body.style.backgroundColor = themeColors[toIdx].bg;
      } else {
        document.body.style.backgroundColor = themeColors[fromIdx].bg;
      }
    }
  }

  // 绘制网格
  function drawGrid() {
    const W = window.innerWidth;
    const H = window.innerHeight;
    gridCtx.clearRect(0, 0, W, H);

    const fromColor = themeColors[currentThemeIdx]?.grid || 'rgba(109, 40, 217, 0.07)';
    const toColor = themeColors[nextThemeIdx]?.grid || 'rgba(109, 40, 217, 0.07)';
    const fromAccent = themeColors[currentThemeIdx]?.accent || '#8b5cf6';
    const toAccent = themeColors[nextThemeIdx]?.accent || '#8b5cf6';

    for (let r = 0; r < gridRows; r++) {
      for (let c = 0; c < gridCols; c++) {
        const x = c * TILE_SIZE;
        const y = r * TILE_SIZE;
        const tile = tiles[r][c];
        const p = tile.flipProgress;

        // 方块的翻转效果：用缩放模拟垂直翻转（上下翻）
        // 进度 0-0.5: 正面缩窄，0.5-1: 背面展开
        let scaleY = 1;
        let color;

        if (p < 0.5) {
          // 前半段：从当前色翻到边缘
          scaleY = 1 - p * 1.6;
          color = fromColor;
        } else {
          // 后半段：从边缘展开到新色
          scaleY = (p - 0.5) * 1.6 + 0.2;
          color = toColor;
        }

        scaleY = Math.max(0.05, Math.min(1, scaleY));

        const drawH = TILE_SIZE * scaleY;
        const drawY = y + (TILE_SIZE - drawH) / 2;

        // 翻转中的方块，填充一点颜色增加立体感
        if (p > 0 && p < 1) {
          gridCtx.fillStyle = color.replace(/[\d.]+\)$/, (parseFloat(color.match(/[\d.]+\)$/)?.[0] || 0.07) * 1.5).toFixed(3) + ')');
          gridCtx.fillRect(x + 0.5, drawY + 0.5, TILE_SIZE - 1, drawH - 1);
        }

        // 网格线（四边）— 细线更细腻
        gridCtx.strokeStyle = color;
        gridCtx.lineWidth = 0.3;
        gridCtx.strokeRect(x + 0.15, drawY + 0.15, TILE_SIZE - 0.3, drawH - 0.3);
      }
    }

    // 径向淡出（让网格从中心向边缘逐渐消失）
    const gradient = gridCtx.createRadialGradient(
      W / 2, H / 2, Math.min(W, H) * 0.25,
      W / 2, H / 2, Math.max(W, H) * 0.65
    );
    gradient.addColorStop(0, 'rgba(0,0,0,0)');
    gradient.addColorStop(1, themeColors[currentThemeIdx]?.bg || '#f8f9fc');

    requestAnimationFrame(drawGrid);
  }
  drawGrid();

  // 滚动监听
  let scrollThrottle = false;
  window.addEventListener('scroll', () => {
    if (!scrollThrottle) {
      scrollThrottle = true;
      requestAnimationFrame(() => {
        updateGridFlip();
        scrollThrottle = false;
      });
    }
  }, { passive: true });

  // 初始化 body 背景
  document.body.style.backgroundColor = themeColors[0].bg;

  // ==========================================
  // 3. 粒子背景
  // ==========================================
  const canvas = document.getElementById('particleCanvas');
  const ctx = canvas.getContext('2d');
  let particles = [];
  let W = 0, H = 0;

  function resizeCanvas() {
    W = canvas.width = window.innerWidth;
    H = canvas.height = window.innerHeight;
    createParticles();
  }

  function createParticles() {
    particles = [];
    const count = Math.floor((W * H) / 18000);
    for (let i = 0; i < count; i++) {
      particles.push({
        x: Math.random() * W,
        y: Math.random() * H,
        vx: (Math.random() - 0.5) * 0.25,
        vy: (Math.random() - 0.5) * 0.25,
        radius: Math.random() * 1.2 + 0.4,
        opacity: Math.random() * 0.4 + 0.15
      });
    }
  }

  function drawParticles() {
    ctx.clearRect(0, 0, W, H);

    // 粒子
    for (let i = 0; i < particles.length; i++) {
      const p = particles[i];
      p.x += p.vx;
      p.y += p.vy;

      if (p.x < 0) p.x = W;
      if (p.x > W) p.x = 0;
      if (p.y < 0) p.y = H;
      if (p.y > H) p.y = 0;

      // 鼠标引力
      const dx = mouseX - p.x;
      const dy = mouseY - p.y;
      const dist = Math.sqrt(dx * dx + dy * dy);
      if (dist < 120) {
        const force = (120 - dist) / 120 * 0.015;
        p.vx += (dx / dist) * force;
        p.vy += (dy / dist) * force;
      }

      // 速度衰减
      p.vx *= 0.99;
      p.vy *= 0.99;

      ctx.beginPath();
      ctx.arc(p.x, p.y, p.radius, 0, Math.PI * 2);
      ctx.fillStyle = `rgba(109, 40, 217, ${p.opacity * 0.5})`;
      ctx.fill();
    }

    // 连线
    for (let i = 0; i < particles.length; i++) {
      for (let j = i + 1; j < particles.length; j++) {
        const dx = particles[i].x - particles[j].x;
        const dy = particles[i].y - particles[j].y;
        const dist = Math.sqrt(dx * dx + dy * dy);
        if (dist < 100) {
          const opacity = (1 - dist / 100) * 0.15;
          ctx.beginPath();
          ctx.moveTo(particles[i].x, particles[i].y);
          ctx.lineTo(particles[j].x, particles[j].y);
          ctx.strokeStyle = `rgba(109, 40, 217, ${opacity * 0.4})`;
          ctx.lineWidth = 0.5;
          ctx.stroke();
        }
      }
    }

    requestAnimationFrame(drawParticles);
  }

  resizeCanvas();
  drawParticles();
  window.addEventListener('resize', resizeCanvas);

  // ==========================================
  // 4. 滚动进度条
  // ==========================================
  const progressBar = document.createElement('div');
  progressBar.className = 'scroll-progress';
  document.body.appendChild(progressBar);

  window.addEventListener('scroll', () => {
    const scrollTop = window.scrollY;
    const docHeight = document.documentElement.scrollHeight - window.innerHeight;
    const progress = (scrollTop / docHeight) * 100;
    progressBar.style.width = progress + '%';
  }, { passive: true });

  // ==========================================
  // 5. 导航栏滚动效果
  // ==========================================
  const navbar = document.querySelector('.navbar');
  const navLinks = document.querySelectorAll('.nav-link');
  const navToggle = document.querySelector('.nav-toggle');
  const navMenu = document.querySelector('.nav-menu');

  window.addEventListener('scroll', () => {
    if (window.scrollY > 50) {
      navbar.classList.add('scrolled');
    } else {
      navbar.classList.remove('scrolled');
    }

    // 导航高亮
    const scrollPos = window.scrollY + 120;
    let currentSection = '';

    sectionList.forEach(section => {
      const top = section.offsetTop;
      const height = section.offsetHeight;
      if (scrollPos >= top && scrollPos < top + height) {
        currentSection = section.getAttribute('id');
      }
    });

    navLinks.forEach(link => {
      link.classList.remove('active');
      if (link.getAttribute('href') === '#' + currentSection) {
        link.classList.add('active');
      }
    });
  }, { passive: true });

  // 移动端菜单
  if (navToggle) {
    navToggle.addEventListener('click', () => {
      navToggle.classList.toggle('active');
      navMenu.classList.toggle('open');
    });

    navLinks.forEach(link => {
      link.addEventListener('click', () => {
        navToggle.classList.remove('active');
        navMenu.classList.remove('open');
      });
    });
  }

  // ==========================================
  // 6. 滚动显示动画 (IntersectionObserver)
  // ==========================================
  const revealElements = document.querySelectorAll('.reveal');
  const levelBars = document.querySelectorAll('.level-bar');

  const revealObserver = new IntersectionObserver((entries) => {
    entries.forEach(entry => {
      if (entry.isIntersecting) {
        entry.target.classList.add('visible');

        // 技能条动画
        if (entry.target.classList.contains('bento-large')) {
          const bar = entry.target.querySelector('.level-bar');
          if (bar) {
            const targetWidth = bar.style.width;
            bar.style.width = '0';
            setTimeout(() => {
              bar.style.width = targetWidth;
            }, 200);
          }
        }
      }
    });
  }, {
    threshold: 0.1,
    rootMargin: '0px 0px -60px 0px'
  });

  revealElements.forEach(el => revealObserver.observe(el));

  // ==========================================
  // 7. 3D 卡片倾斜效果
  // ==========================================
  const tiltCards = document.querySelectorAll('.tilt-card, .project-card, .idea-card, .note-card, .contact-item');

  tiltCards.forEach(card => {
    card.addEventListener('mousemove', (e) => {
      const rect = card.getBoundingClientRect();
      const x = e.clientX - rect.left;
      const y = e.clientY - rect.top;
      const centerX = rect.width / 2;
      const centerY = rect.height / 2;
      const rotateX = (y - centerY) / 25;
      const rotateY = (centerX - x) / 25;

      card.style.transform = `perspective(1000px) rotateX(${rotateX}deg) rotateY(${rotateY}deg) translateY(-6px) scale(1.015)`;
    });

    card.addEventListener('mouseleave', () => {
      card.style.transform = '';
    });
  });

  // ==========================================
  // 8. 项目筛选
  // ==========================================
  const filterBtns = document.querySelectorAll('.filter-btn');
  const projectCards = document.querySelectorAll('.project-card');

  filterBtns.forEach(btn => {
    btn.addEventListener('click', () => {
      filterBtns.forEach(b => b.classList.remove('active'));
      btn.classList.add('active');

      const filter = btn.getAttribute('data-filter');

      projectCards.forEach(card => {
        const type = card.getAttribute('data-type');
        if (filter === 'all' || filter === type) {
          card.classList.remove('hidden');
          card.style.animation = 'fadeInUp 0.5s ease both';
        } else {
          card.classList.add('hidden');
        }
      });
    });
  });

  // ==========================================
  // 9. 数字计数动画
  // ==========================================
  const counters = document.querySelectorAll('.mini-num');

  function animateCounter(el) {
    const target = parseInt(el.getAttribute('data-target') || el.textContent);
    const duration = 1800;
    const start = performance.now();

    function step(now) {
      const progress = Math.min((now - start) / duration, 1);
      const eased = 1 - Math.pow(1 - progress, 3);
      const current = Math.floor(eased * target);
      el.textContent = current + (el.getAttribute('data-suffix') || '');
      if (progress < 1) requestAnimationFrame(step);
    }
    requestAnimationFrame(step);
  }

  const counterObserver = new IntersectionObserver((entries) => {
    entries.forEach(entry => {
      if (entry.isIntersecting) {
        const stats = entry.target.querySelectorAll('.mini-num');
        stats.forEach(s => animateCounter(s));
        counterObserver.unobserve(entry.target);
      }
    });
  }, { threshold: 0.5 });

  const statsRow = document.querySelector('.hero-stats-row');
  if (statsRow) counterObserver.observe(statsRow);

  // ==========================================
  // 10. Hero 视差效果
  // ==========================================
  const heroOrb = document.querySelector('.hero-orb');
  const floatTags = document.querySelectorAll('.float-tag');
  const heroGlows = document.querySelectorAll('.hero-glow');

  document.addEventListener('mousemove', (e) => {
    const x = (e.clientX / window.innerWidth - 0.5) * 2;
    const y = (e.clientY / window.innerHeight - 0.5) * 2;

    if (heroOrb) {
      heroOrb.style.transform = `translate(${x * 20}px, ${y * 20}px)`;
    }

    floatTags.forEach((tag, i) => {
      const factor = (i + 1) * 6;
      tag.style.transform = `translate(${x * factor}px, ${y * factor}px)`;
    });

    heroGlows.forEach((glow, i) => {
      const factor = (i + 1) * 15;
      glow.style.transform = `translate(${x * factor}px, ${y * factor}px)`;
    });
  });

  // ==========================================
  // 11. 回到顶部
  // ==========================================
  const backToTop = document.querySelector('.back-to-top');

  window.addEventListener('scroll', () => {
    if (window.scrollY > 500) {
      backToTop.classList.add('visible');
    } else {
      backToTop.classList.remove('visible');
    }
  }, { passive: true });

  if (backToTop) {
    backToTop.addEventListener('click', () => {
      window.scrollTo({ top: 0, behavior: 'smooth' });
    });
  }

  // ==========================================
  // 12. 表单提交
  // ==========================================
  const contactForm = document.querySelector('.contact-form form');
  if (contactForm) {
    contactForm.addEventListener('submit', (e) => {
      e.preventDefault();
      const btn = contactForm.querySelector('button[type="submit"]');
      const originalText = btn.innerHTML;
      btn.innerHTML = '<span class="btn-text-deco">[</span>发送中...<span class="btn-text-deco">]</span>';
      btn.disabled = true;

      setTimeout(() => {
        btn.innerHTML = '<span class="btn-text-deco">[</span>已收到！<span class="btn-arrow">✓</span><span class="btn-text-deco">]</span>';
        btn.style.background = 'var(--gradient-3)';

        setTimeout(() => {
          btn.innerHTML = originalText;
          btn.disabled = false;
          btn.style.background = '';
          contactForm.reset();
        }, 2500);
      }, 1200);
    });
  }

  // ==========================================
  // 13. 平滑滚动
  // ==========================================
  document.querySelectorAll('a[href^="#"]').forEach(anchor => {
    anchor.addEventListener('click', function (e) {
      e.preventDefault();
      const target = document.querySelector(this.getAttribute('href'));
      if (target) {
        target.scrollIntoView({
          behavior: 'smooth',
          block: 'start'
        });
      }
    });
  });

  // ==========================================
  // 14. 中英文切换
  // ==========================================
  const i18n = {
    zh: {
      'nav.about': '概览',
      'nav.skills': '方向',
      'nav.projects': '项目',
      'nav.ideas': '创意',
      'nav.notes': '研究',
      'nav.contact': '交流',
      'visit.total': '总访问',
      'visit.last': '最近',
      'visit.online': '在线',
      'hero.tag': 'CREATIVE RESEARCH LAB / 创意研究实验室',
      'hero.line1': '探索',
      'hero.line2': '创意与设计',
      'hero.line3': '的边界',
      'hero.desc': '一个面向创意与技术的开放实验平台 —— 聚焦 AI 探索、创意设计、数据洞察、全栈开发、交互体验、硬件创新与游戏实验。<br/>在这里，想法被验证，原型被构建，边界被推动。',
      'hero.btn1': '浏览创意项目',
      'hero.btn2.sub': '前沿想法',
      'hero.stat1.label': '创意项目',
      'hero.stat2.label': '研究笔记',
      'hero.stat3.label': '开源仓库',
      'hero.stat4.label': '探索方向',
      'skills.title.p1': '研究',
      'skills.title.p2': '方向',
      'skills.subtitle': '从人工智能到硬件创新，跨学科探索，持续扩展中...',
      'projects.title.p1': '创意',
      'projects.title.p2': '项目',
      'projects.subtitle': '跨越多个领域的实验项目与开源作品',
      'filter.all': '全部',
      'filter.mobile': '移动端',
      'ideas.title.p1': '前沿',
      'ideas.title.p2': '创意',
      'ideas.title.p3': '探索',
      'ideas.subtitle': '待验证的假设、跨学科的思考、以及对未来技术的展望。欢迎参与讨论！',
      'notes.title.p1': '研究',
      'notes.title.p2': '笔记',
      'notes.subtitle': '技术洞察、算法推导、设计思考与研究总结',
      'contact.title.p1': '提交与',
      'contact.title.p2': '交流',
      'contact.desc': '有创意想法想要落地？对某个方向有独到见解？欢迎提交与交流，我们相信好的想法值得被实现。',
      'footer.desc': '一个面向创意与技术的开放研究平台，持续探索算法、设计与创新的边界。',
      'footer.col1': '导航',
      'footer.col2': '资源',
      'footer.col3': '交流',
      'footer.copyright': '© 2025 Creative Research Lab. All rights reserved.',
      'footer.motto': '探索不止，创新不息。',
      'form.nameLabel': '姓名',
      'form.name': '你的名字',
      'form.emailLabel': '邮箱',
      'form.subjectLabel': '主题',
      'form.subject': '想聊点什么？',
      'form.messageLabel': '内容',
      'form.message': '随便说点什么...',
      'form.submit': '提交消息',
      'help.title': '关于本站',
      'help.what.title': '这是什么？',
      'help.what.desc': '一个面向创意与技术的开放研究平台，聚焦 AI 探索、算法设计、数据洞察、全栈开发、交互设计、硬件创新与游戏实验。',
      'help.features.title': '核心内容',
      'help.features.1': '🧠 AI 探索与算法研究',
      'help.features.2': '📊 数据科学与可视化',
      'help.features.3': '💻 全栈开发与工程实践',
      'help.features.4': '🎨 交互设计与创意实验',
      'help.features.5': '🔌 硬件创新与物联网',
      'help.features.6': '🎮 游戏开发与交互艺术',
      'help.features.7': '📚 技术研究笔记与文献',
      'help.features.8': '💡 前沿想法与未来展望',
      'help.usage.title': '如何使用',
      'help.usage.1': '🖱 滚动页面浏览各板块内容',
      'help.usage.2': '🌐 点击右上角「中 / EN」切换语言',
      'help.usage.3': '📬 有想法？通过「提交与交流」板块发送',
      'help.usage.4': '⚡ 滚动时可观察网格翻砖过渡特效',
      'help.contact.title': '联系方式'
    },
    en: {
      'nav.about': 'Overview',
      'nav.skills': 'Focus',
      'nav.projects': 'Projects',
      'nav.ideas': 'Ideas',
      'nav.notes': 'Research',
      'nav.contact': 'Connect',
      'visit.total': 'Visits',
      'visit.last': 'Last',
      'visit.online': 'Online',
      'hero.tag': 'CREATIVE RESEARCH LAB',
      'hero.line1': 'Exploring',
      'hero.line2': 'the edge of',
      'hero.line3': 'ideas & design',
      'hero.desc': 'An open experimental platform for creativity and technology — focused on AI exploration, creative design, data insights, full-stack development, interaction experience, hardware innovation and game experiments.<br/>Where ideas are validated, prototypes are built, and boundaries are pushed.',
      'hero.btn1': 'Explore Projects',
      'hero.btn2.sub': 'Frontier Ideas',
      'hero.stat1.label': 'Projects',
      'hero.stat2.label': 'Papers',
      'hero.stat3.label': 'Repos',
      'hero.stat4.label': 'Directions',
      'skills.title.p1': 'Research',
      'skills.title.p2': 'Areas',
      'skills.subtitle': 'From AI to hardware innovation — interdisciplinary exploration',
      'projects.title.p1': 'Creative',
      'projects.title.p2': 'Projects',
      'projects.subtitle': 'Experimental projects and open-source works across disciplines',
      'filter.all': 'All',
      'filter.mobile': 'Mobile',
      'ideas.title.p1': 'Frontier',
      'ideas.title.p2': 'Ideas',
      'ideas.title.p3': '& Vision',
      'ideas.subtitle': 'Hypotheses to validate, interdisciplinary thinking, and visions for future tech.',
      'notes.title.p1': 'Research',
      'notes.title.p2': 'Notes',
      'notes.subtitle': 'Technical insights, algorithm derivations, and design reflections',
      'contact.title.p1': 'Submit &',
      'contact.title.p2': 'Connect',
      'contact.desc': 'Have a creative idea to build? A unique perspective to share? We believe good ideas deserve to be realized.',
      'footer.desc': 'An open research platform for creativity and technology — pushing the boundaries of algorithms, design and innovation.',
      'footer.col1': 'Navigate',
      'footer.col2': 'Resources',
      'footer.col3': 'Connect',
      'footer.copyright': '© 2025 Creative Research Lab. All rights reserved.',
      'footer.motto': 'Explore endlessly, innovate ceaselessly.',
      'form.nameLabel': 'Name',
      'form.name': 'Your name',
      'form.emailLabel': 'Email',
      'form.subjectLabel': 'Subject',
      'form.subject': 'What would you like to share?',
      'form.messageLabel': 'Message',
      'form.message': 'Share your thoughts...',
      'form.submit': 'Submit',
      'help.title': 'About This Site',
      'help.what.title': 'What is this?',
      'help.what.desc': 'An open research platform for creativity and technology — focused on AI exploration, algorithm design, data insights, full-stack development, interaction design, hardware innovation and game experiments.',
      'help.features.title': 'Core Areas',
      'help.features.1': '🧠 AI Research & Algorithm Design',
      'help.features.2': '📊 Data Science & Visualization',
      'help.features.3': '💻 Full-Stack Development',
      'help.features.4': '🎨 Interaction Design & Creative Experiments',
      'help.features.5': '🔌 Hardware Innovation & IoT',
      'help.features.6': '🎮 Game Dev & Interactive Art',
      'help.features.7': '📚 Research Notes & Papers',
      'help.features.8': '💡 Frontier Ideas & Future Vision',
      'help.usage.title': 'How to Use',
      'help.usage.1': '🖱 Scroll to explore different sections',
      'help.usage.2': '🌐 Click "中 / EN" in the top-right to switch language',
      'help.usage.3': '📬 Submit ideas via the "Submit & Connect" section',
      'help.usage.4': '⚡ Watch for the grid tile transition when scrolling',
      'help.contact.title': 'Contact'
    }
  };

  let currentLang = localStorage.getItem('ycc-lang') || 'zh';

  function applyLang(lang) {
    currentLang = lang;
    localStorage.setItem('ycc-lang', lang);
    const dict = i18n[lang];
    // 文本内容
    document.querySelectorAll('[data-i18n]').forEach(el => {
      const key = el.getAttribute('data-i18n');
      if (dict[key]) {
        el.innerHTML = dict[key];
      }
    });
    // placeholder
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
      const key = el.getAttribute('data-i18n-placeholder');
      if (dict[key]) {
        el.placeholder = dict[key];
      }
    });
    // 更新语言按钮状态
    const langToggle = document.getElementById('langToggle');
    if (langToggle) {
      langToggle.querySelector('.lang-cn').classList.toggle('active', lang === 'zh');
      langToggle.querySelector('.lang-en').classList.toggle('active', lang === 'en');
    }
  }

  const langToggle = document.getElementById('langToggle');
  if (langToggle) {
    langToggle.addEventListener('click', () => {
      const newLang = currentLang === 'zh' ? 'en' : 'zh';
      applyLang(newLang);
    });
  }

  // 初始化语言
  applyLang(currentLang);

  // ==========================================
  // 15. 访问统计
  // ==========================================
  function updateVisitStats() {
    const VISIT_KEY = 'ycc_visit_stats';
    let stats = JSON.parse(localStorage.getItem(VISIT_KEY) || '{}');

    // 初始化
    if (!stats.total) {
      stats = {
        total: Math.floor(Math.random() * 500) + 1200, // 初始基数
        lastVisit: Date.now(),
        online: 1
      };
    }

    // 新的一次访问（距离上次超过 30 分钟算一次新访问）
    const now = Date.now();
    if (now - stats.lastVisit > 30 * 60 * 1000) {
      stats.total += 1;
    }
    stats.lastVisit = now;
    localStorage.setItem(VISIT_KEY, JSON.stringify(stats));

    // 更新显示
    const totalEl = document.getElementById('visitTotal');
    const lastEl = document.getElementById('visitLast');
    const onlineEl = document.getElementById('visitOnline');

    if (totalEl) {
      animateNumber(totalEl, stats.total);
    }
    if (lastEl) {
      const d = new Date(stats.lastVisit);
      const pad = n => n.toString().padStart(2, '0');
      lastEl.textContent = `${pad(d.getMonth()+1)}/${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`;
    }
    if (onlineEl) {
      // 模拟在线人数：1-3 人
      const online = Math.floor(Math.random() * 3) + 1;
      onlineEl.textContent = online;
    }
  }

  function animateNumber(el, target) {
    const start = parseInt(el.textContent) || 0;
    const duration = 1500;
    const startTime = performance.now();

    function step(currentTime) {
      const elapsed = currentTime - startTime;
      const progress = Math.min(elapsed / duration, 1);
      const eased = 1 - Math.pow(1 - progress, 3);
      const current = Math.floor(start + (target - start) * eased);
      el.textContent = current.toLocaleString();
      if (progress < 1) {
        requestAnimationFrame(step);
      }
    }
    requestAnimationFrame(step);
  }

  updateVisitStats();

  // ==========================================
  // 16. 帮助弹窗
  // ==========================================
  const helpBtn = document.getElementById('helpBtn');
  const helpModal = document.getElementById('helpModal');
  const helpModalClose = document.getElementById('helpModalClose');
  const helpModalOverlay = document.getElementById('helpModalOverlay');

  function openHelpModal() {
    if (helpModal) {
      helpModal.classList.add('active');
      document.body.style.overflow = 'hidden';
    }
  }

  function closeHelpModal() {
    if (helpModal) {
      helpModal.classList.remove('active');
      document.body.style.overflow = '';
    }
  }

  if (helpBtn) helpBtn.addEventListener('click', openHelpModal);
  if (helpModalClose) helpModalClose.addEventListener('click', closeHelpModal);
  if (helpModalOverlay) helpModalOverlay.addEventListener('click', closeHelpModal);

  // ESC 关闭
  document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape' && helpModal?.classList.contains('active')) {
      closeHelpModal();
    }
  });

  // ==========================================
  // 17. 左侧悬浮飘动标签
  // ==========================================
  const tagsCanvas = document.getElementById('floatTagsCanvas');
  if (tagsCanvas) {
    const tagsCtx = tagsCanvas.getContext('2d');

    // 关键词标签库（多分类）
    const tagPool = [
      // —— AI / 机器学习 ——
      { text: 'AI', size: 'lg', category: 'ai' },
      { text: '深度学习', size: 'lg', category: 'ai' },
      { text: '大语言模型', size: 'md', category: 'ai' },
      { text: '计算机视觉', size: 'md', category: 'ai' },
      { text: '神经网络', size: 'sm', category: 'ai' },
      { text: 'Transformer', size: 'sm', category: 'ai' },
      { text: '扩散模型', size: 'sm', category: 'ai' },
      { text: '强化学习', size: 'sm', category: 'ai' },
      { text: 'Agent', size: 'md', category: 'ai' },
      { text: '智能体', size: 'sm', category: 'ai' },
      { text: '知识库', size: 'sm', category: 'ai' },
      { text: 'RAG', size: 'sm', category: 'ai' },
      { text: '多模态', size: 'sm', category: 'ai' },
      { text: 'Prompt', size: 'sm', category: 'ai' },
      { text: '模型微调', size: 'sm', category: 'ai' },

      // —— 算法 / 数据 ——
      { text: '算法设计', size: 'md', category: 'algo' },
      { text: '分类', size: 'sm', category: 'algo' },
      { text: '聚类', size: 'sm', category: 'algo' },
      { text: '预测', size: 'sm', category: 'algo' },
      { text: '规划', size: 'sm', category: 'algo' },
      { text: '大数据', size: 'md', category: 'algo' },
      { text: '数据挖掘', size: 'sm', category: 'algo' },
      { text: '数据分析', size: 'sm', category: 'algo' },
      { text: '可视化', size: 'sm', category: 'algo' },
      { text: '爬虫', size: 'sm', category: 'algo' },
      { text: '数据库', size: 'sm', category: 'algo' },
      { text: '数据结构', size: 'sm', category: 'algo' },
      { text: '数学建模', size: 'sm', category: 'algo' },
      { text: '概率论', size: 'sm', category: 'algo' },
      { text: '图论', size: 'sm', category: 'algo' },

      // —— 开发 / 工程 ——
      { text: '全栈开发', size: 'md', category: 'dev' },
      { text: '前端', size: 'sm', category: 'dev' },
      { text: '后端', size: 'sm', category: 'dev' },
      { text: '交互设计', size: 'sm', category: 'dev' },
      { text: '架构设计', size: 'sm', category: 'dev' },
      { text: '微服务', size: 'sm', category: 'dev' },
      { text: '云原生', size: 'sm', category: 'dev' },
      { text: 'DevOps', size: 'sm', category: 'dev' },
      { text: '开源', size: 'sm', category: 'dev' },
      { text: '性能优化', size: 'sm', category: 'dev' },
      { text: '工程化', size: 'sm', category: 'dev' },

      // —— 应用场景 ——
      { text: '智能监控', size: 'sm', category: 'app' },
      { text: '健康管理', size: 'sm', category: 'app' },
      { text: '远程控制', size: 'sm', category: 'app' },
      { text: '自动驾驶', size: 'sm', category: 'app' },
      { text: '智慧医疗', size: 'sm', category: 'app' },
      { text: '金融科技', size: 'sm', category: 'app' },
      { text: '推荐系统', size: 'sm', category: 'app' },
      { text: '语义理解', size: 'sm', category: 'app' },
      { text: '图像生成', size: 'sm', category: 'app' },
      { text: '语音识别', size: 'sm', category: 'app' },

      // —— 研究 / 论文 ——
      { text: '论文研读', size: 'sm', category: 'research' },
      { text: '创新实验', size: 'sm', category: 'research' },
      { text: '前沿探索', size: 'sm', category: 'research' },
      { text: '技术展望', size: 'sm', category: 'research' },
      { text: '原型设计', size: 'sm', category: 'research' },
      { text: '创意实现', size: 'md', category: 'research' },

      // —— 生活 / 兴趣 ——
      { text: '摄影', size: 'md', category: 'life' },
      { text: '旅行', size: 'md', category: 'life' },
      { text: '乒乓球', size: 'sm', category: 'life' },
      { text: '羽毛球', size: 'sm', category: 'life' },
      { text: '跑步', size: 'sm', category: 'life' },
      { text: '游泳', size: 'sm', category: 'life' },
      { text: '骑行', size: 'sm', category: 'life' },
      { text: '登山', size: 'sm', category: 'life' },
      { text: '电影', size: 'sm', category: 'life' },
      { text: '音乐', size: 'sm', category: 'life' },
      { text: '阅读', size: 'sm', category: 'life' },
      { text: '写作', size: 'sm', category: 'life' },
      { text: '烹饪', size: 'sm', category: 'life' },
      { text: '手冲咖啡', size: 'sm', category: 'life' },
      { text: '独立游戏', size: 'sm', category: 'life' },
      { text: 'RPG', size: 'sm', category: 'life' },
      { text: 'FPS', size: 'sm', category: 'life' },
      { text: 'MOBA', size: 'sm', category: 'life' },
      { text: '策略游戏', size: 'sm', category: 'life' },
      { text: '沙盒游戏', size: 'sm', category: 'life' },
    ];

    // 分类对应颜色
    const tagColors = {
      ai:       { fill: 'rgba(139, 92, 246, 0.9)',  stroke: 'rgba(139, 92, 246, 0.4)' },
      algo:     { fill: 'rgba(8, 145, 178, 0.9)',   stroke: 'rgba(8, 145, 178, 0.4)' },
      dev:      { fill: 'rgba(219, 39, 119, 0.9)',  stroke: 'rgba(219, 39, 119, 0.4)' },
      app:      { fill: 'rgba(5, 150, 105, 0.9)',   stroke: 'rgba(5, 150, 105, 0.4)' },
      research: { fill: 'rgba(217, 119, 6, 0.9)',   stroke: 'rgba(217, 119, 6, 0.4)' },
      life:     { fill: 'rgba(107, 114, 128, 0.9)', stroke: 'rgba(107, 114, 128, 0.4)' },
    };

    const sizeMap = { lg: 20, md: 15, sm: 12 };

    let tags = [];
    let tagW = 0, tagH = 0;

    function initTags() {
      const canvas = tagsCanvas;
      tagW = canvas.offsetWidth;
      tagH = canvas.offsetHeight;
      canvas.width = tagW * window.devicePixelRatio;
      canvas.height = tagH * window.devicePixelRatio;
      tagsCtx.scale(window.devicePixelRatio, window.devicePixelRatio);

      // 随机选取 35-45 个标签
      const count = Math.min(tagPool.length, 35 + Math.floor(Math.random() * 10));
      const shuffled = [...tagPool].sort(() => Math.random() - 0.5).slice(0, count);

      tags = shuffled.map((tag, i) => {
        const fontSize = sizeMap[tag.size] || 14;
        return {
          text: tag.text,
          category: tag.category,
          fontSize: fontSize,
          x: Math.random() * tagW,
          y: Math.random() * tagH,
          vx: (Math.random() - 0.5) * 0.3,  // 水平速度，很慢
          vy: (Math.random() - 0.5) * 0.15, // 垂直速度，更慢
          phase: Math.random() * Math.PI * 2, // 摆动相位
          swaySpeed: 0.005 + Math.random() * 0.01, // 摆动速度
          swayAmp: 8 + Math.random() * 15,       // 摆动幅度
          opacity: 0.4 + Math.random() * 0.5,
          rot: (Math.random() - 0.5) * 0.15, // 轻微倾斜
        };
      });
    }

    function drawTags() {
      tagsCtx.clearRect(0, 0, tagW, tagH);

      const time = performance.now() * 0.001;

      tags.forEach(tag => {
        // 基础移动
        tag.x += tag.vx;
        tag.y += tag.vy;

        // 叠加正弦摆动（上下飘动）
        const swayY = Math.sin(time * tag.swaySpeed * 60 + tag.phase) * tag.swayAmp * 0.3;
        const swayX = Math.cos(time * tag.swaySpeed * 30 + tag.phase * 1.3) * tag.swayAmp * 0.2;

        // 边界反弹
        if (tag.x < 20 || tag.x > tagW - 20) tag.vx *= -1;
        if (tag.y < 30 || tag.y > tagH - 30) tag.vy *= -1;

        const drawX = tag.x + swayX;
        const drawY = tag.y + swayY;

        const colors = tagColors[tag.category] || tagColors.ai;

        tagsCtx.save();
        tagsCtx.translate(drawX, drawY);
        tagsCtx.rotate(tag.rot);
        tagsCtx.globalAlpha = tag.opacity;

        // 文字描边（增加立体感）
        tagsCtx.font = `600 ${tag.fontSize}px "Noto Sans SC", "ZCOOL XiaoWei", sans-serif`;
        tagsCtx.textAlign = 'center';
        tagsCtx.textBaseline = 'middle';

        // 外发光
        tagsCtx.shadowColor = colors.fill;
        tagsCtx.shadowBlur = 8;

        tagsCtx.fillStyle = colors.fill;
        tagsCtx.fillText(tag.text, 0, 0);

        tagsCtx.shadowBlur = 0;
        tagsCtx.restore();
      });

      requestAnimationFrame(drawTags);
    }

    // 初始化
    initTags();
    drawTags();

    // 窗口变化重排
    let resizeTimer = null;
    window.addEventListener('resize', () => {
      clearTimeout(resizeTimer);
      resizeTimer = setTimeout(initTags, 300);
    });
  }

  // ==========================================
  // 18. 音乐播放器 + 网格可视化
  // ==========================================
  const musicPlayer = document.getElementById('musicPlayer');
  const musicToggle = document.getElementById('musicToggle');
  const musicPanel = document.getElementById('musicPanel');
  const musicPlayBtn = document.getElementById('musicPlayBtn');
  const bgMusic = document.getElementById('bgMusic');
  const musicProgress = document.getElementById('musicProgress');
  const musicProgressBar = document.getElementById('musicProgressBar');
  const musicProgressThumb = document.getElementById('musicProgressThumb');
  const musicCurrent = document.getElementById('musicCurrent');
  const musicDuration = document.getElementById('musicDuration');
  const volumeSlider = document.getElementById('volumeSlider');
  const volumeBar = document.getElementById('volumeBar');

  let audioCtx = null;
  let analyser = null;
  let sourceNode = null;
  let dataArray = null;
  let bufferLength = 0;
  let musicVisualActive = false;

  // 切换面板展开/收起
  if (musicToggle) {
    musicToggle.addEventListener('click', () => {
      musicPlayer.classList.toggle('open');
    });
  }

  // 初始化音频分析
  function initAudioAnalyser() {
    if (audioCtx) return;
    try {
      audioCtx = new (window.AudioContext || window.webkitAudioContext)();
      analyser = audioCtx.createAnalyser();
      analyser.fftSize = 256;
      bufferLength = analyser.frequencyBinCount;
      dataArray = new Uint8Array(bufferLength);
      sourceNode = audioCtx.createMediaElementSource(bgMusic);
      sourceNode.connect(analyser);
      analyser.connect(audioCtx.destination);
    } catch (e) {
      console.warn('Audio context not supported');
    }
  }

  // 播放/暂停
  if (musicPlayBtn) {
    musicPlayBtn.addEventListener('click', () => {
      if (!audioCtx) initAudioAnalyser();
      if (audioCtx && audioCtx.state === 'suspended') {
        audioCtx.resume();
      }
      if (bgMusic.paused) {
        bgMusic.play().then(() => {
          musicPlayer.classList.add('playing');
          musicToggle.classList.add('playing');
          musicVisualActive = true;
        }).catch(err => {
          console.warn('播放失败:', err);
        });
      } else {
        bgMusic.pause();
        musicPlayer.classList.remove('playing');
        musicToggle.classList.remove('playing');
        musicVisualActive = false;
      }
    });
  }

  // 格式化时间
  function formatTime(seconds) {
    const m = Math.floor(seconds / 60);
    const s = Math.floor(seconds % 60);
    return m + ':' + (s < 10 ? '0' + s : s);
  }

  // 元数据加载完成 + 主动预加载
  if (bgMusic) {
    // 页面加载后主动开始缓冲音频，减少首次播放延迟
    try { bgMusic.load(); } catch(e) {}

    bgMusic.addEventListener('loadedmetadata', () => {
      if (musicDuration) musicDuration.textContent = formatTime(bgMusic.duration);
    });

    // 进度更新
    bgMusic.addEventListener('timeupdate', () => {
      const pct = (bgMusic.currentTime / bgMusic.duration) * 100;
      if (musicProgressBar) musicProgressBar.style.width = pct + '%';
      if (musicProgressThumb) musicProgressThumb.style.left = pct + '%';
      if (musicCurrent) musicCurrent.textContent = formatTime(bgMusic.currentTime);
    });

    // 结束时重置
    bgMusic.addEventListener('ended', () => {
      musicPlayer.classList.remove('playing');
      musicToggle.classList.remove('playing');
      musicVisualActive = false;
    });
  }

  // 进度条点击跳转
  if (musicProgress) {
    musicProgress.addEventListener('click', (e) => {
      const rect = musicProgress.getBoundingClientRect();
      const pct = (e.clientX - rect.left) / rect.width;
      if (bgMusic.duration) {
        bgMusic.currentTime = pct * bgMusic.duration;
      }
    });
  }

  // 音量控制
  if (bgMusic) bgMusic.volume = 0.7;

  if (volumeSlider) {
    volumeSlider.addEventListener('click', (e) => {
      const rect = volumeSlider.getBoundingClientRect();
      const pct = Math.max(0, Math.min(1, (e.clientX - rect.left) / rect.width));
      if (bgMusic) bgMusic.volume = pct;
      if (volumeBar) volumeBar.style.width = (pct * 100) + '%';
    });
  }

  // 获取音乐频率数据，返回低频到中频的平均能量 (0-1)
  function getMusicEnergy() {
    if (!musicVisualActive || !analyser || !dataArray) return 0;
    analyser.getByteFrequencyData(dataArray);
    // 取低频到中低频（前 1/3）作为节拍能量
    let sum = 0;
    const bassEnd = Math.floor(bufferLength * 0.35);
    for (let i = 0; i < bassEnd; i++) {
      sum += dataArray[i];
    }
    return sum / bassEnd / 255; // 0-1
  }

  // 让网格随音乐跳动：修改 drawGrid 中每块砖的翻转/缩放
  // 在 drawGrid 里调用：如果 musicVisualActive，根据频率给 tile 增加跳动效果
  const originalDrawGrid = drawGrid;
  function enhancedDrawGrid() {
    const W = window.innerWidth;
    const H = window.innerHeight;
    gridCtx.clearRect(0, 0, W, H);

    const fromColor = themeColors[currentThemeIdx]?.grid || 'rgba(109, 40, 217, 0.07)';
    const toColor = themeColors[nextThemeIdx]?.grid || 'rgba(109, 40, 217, 0.07)';

    // 获取音乐能量
    const energy = getMusicEnergy();
    const bassBoost = energy * 0.6; // 音乐越响，跳动越强（调小幅度）

    for (let r = 0; r < gridRows; r++) {
      for (let c = 0; c < gridCols; c++) {
        const x = c * TILE_SIZE;
        const y = r * TILE_SIZE;
        const tile = tiles[r][c];
        const p = tile.flipProgress;

        // 音乐跳动：根据每块砖的位置和当前频率，计算额外的"弹跳"幅度
        // 越靠近底部的砖，对低频越敏感
        const rowFactor = 1 - (r / gridRows); // 底部=1，顶部=0
        let musicPulse = 0;

        if (musicVisualActive && dataArray) {
          // 不同列对应不同频率带
          const freqIndex = Math.floor((c / gridCols) * bufferLength * 0.6);
          const freqValue = dataArray[Math.min(freqIndex, bufferLength - 1)] / 255;
          // 底部行对低频更敏感（整体幅度调小）
          musicPulse = freqValue * rowFactor * bassBoost * 0.25;
        }

        // 合并翻砖进度和音乐跳动
        const totalP = Math.min(1, p + musicPulse * 0.15);
        let scaleX = 1;
        let scaleY = 1;
        let color;

        if (totalP < 0.5) {
          scaleX = 1 - totalP * 1.2;
          scaleY = 1 + musicPulse * 0.12;
          color = fromColor;
        } else {
          scaleX = (totalP - 0.5) * 1.2 + 0.4;
          scaleY = 1 + musicPulse * 0.12;
          color = toColor;
        }

        scaleX = Math.max(0.2, Math.min(1.05, scaleX));
        scaleY = Math.max(0.95, Math.min(1.15, scaleY));

        const drawW = TILE_SIZE * scaleX;
        const drawH = TILE_SIZE * scaleY;
        const drawX = x + (TILE_SIZE - drawW) / 2;
        const drawY = y + (TILE_SIZE - drawH) / 2;

        // 音乐模式下增加发光效果（调小幅度）
        if (musicVisualActive && musicPulse > 0.04) {
          gridCtx.shadowColor = themeColors[currentThemeIdx]?.accent || '#8b5cf6';
          gridCtx.shadowBlur = musicPulse * 5;
        } else {
          gridCtx.shadowBlur = 0;
        }

        if (totalP > 0 && totalP < 1) {
          const alphaMatch = color.match(/[\d.]+\)$/);
          const baseAlpha = parseFloat(alphaMatch?.[0] || 0.07);
          const fillAlpha = Math.min(0.2, baseAlpha * 2 + musicPulse * 0.06);
          gridCtx.fillStyle = color.replace(/[\d.]+\)$/, fillAlpha.toFixed(3) + ')');
          gridCtx.fillRect(drawX + 0.5, drawY + 0.5, drawW - 1, drawH - 1);
        }

        gridCtx.strokeStyle = color;
        gridCtx.lineWidth = 0.3;
        gridCtx.strokeRect(drawX + 0.15, drawY + 0.15, drawW - 0.3, drawH - 0.3);
      }
    }

    gridCtx.shadowBlur = 0;
    requestAnimationFrame(enhancedDrawGrid);
  }

  // 替换 drawGrid
  if (typeof drawGrid === 'function') {
    // 取消原有的 requestAnimationFrame
    // 用新的增强版替代
    window.drawGrid = enhancedDrawGrid;
    requestAnimationFrame(enhancedDrawGrid);
  }

});
