// Generated by Trae Work
// YCC's Lab - Creative Developer Lab v3.0

document.addEventListener('DOMContentLoaded', function () {
  'use strict';


  // ==========================================
  // 1. 流星尾迹鼠标效果
  // ==========================================
  const trailCanvas = document.getElementById('trailCanvas');
  const trailCtx = trailCanvas.getContext('2d');
  let trailParticles = [];
  let mouseX = 0, mouseY = 0;
  let lastMouseX = 0, lastMouseY = 0;
  let mouseSpeed = 0;

  function resizeTrailCanvas() {
    trailCanvas.width = window.innerWidth;
    trailCanvas.height = window.innerHeight;
  }
  resizeTrailCanvas();
  window.addEventListener('resize', resizeTrailCanvas);

  document.addEventListener('mousemove', (e) => {
    lastMouseX = mouseX;
    lastMouseY = mouseY;
    mouseX = e.clientX;
    mouseY = e.clientY;

    // 计算鼠标速度
    const dx = mouseX - lastMouseX;
    const dy = mouseY - lastMouseY;
    mouseSpeed = Math.min(Math.sqrt(dx * dx + dy * dy), 30);

    // 根据速度生成粒子
    if (mouseSpeed > 2) {
      const count = Math.floor(mouseSpeed / 4) + 1;
      for (let i = 0; i < count; i++) {
        createTrailParticle(
          mouseX + (Math.random() - 0.5) * 10,
          mouseY + (Math.random() - 0.5) * 10
        );
      }
    }
  });

  function createTrailParticle(x, y) {
    const colors = [
      'rgba(139, 92, 246, ',
      'rgba(167, 139, 250, ',
      'rgba(6, 182, 212, ',
      'rgba(244, 114, 182, '
    ];
    trailParticles.push({
      x: x,
      y: y,
      vx: (Math.random() - 0.5) * 1.5,
      vy: (Math.random() - 0.5) * 1.5 - 0.5,
      radius: Math.random() * 3 + 1.5,
      life: 1,
      decay: Math.random() * 0.02 + 0.012,
      color: colors[Math.floor(Math.random() * colors.length)]
    });

    if (trailParticles.length > 200) {
      trailParticles.shift();
    }
  }

  function animateTrail() {
    trailCtx.clearRect(0, 0, trailCanvas.width, trailCanvas.height);

    // 绘制尾迹连线
    if (trailParticles.length > 1) {
      trailCtx.beginPath();
      trailCtx.moveTo(trailParticles[0].x, trailParticles[0].y);
      for (let i = 1; i < trailParticles.length; i++) {
        const p = trailParticles[i];
        if (p.life > 0.3) {
          trailCtx.lineTo(p.x, p.y);
        }
      }
      trailCtx.strokeStyle = 'rgba(139, 92, 246, 0.15)';
      trailCtx.lineWidth = 2;
      trailCtx.lineCap = 'round';
      trailCtx.lineJoin = 'round';
      trailCtx.stroke();
    }

    // 绘制粒子
    for (let i = trailParticles.length - 1; i >= 0; i--) {
      const p = trailParticles[i];
      p.x += p.vx;
      p.y += p.vy;
      p.vy += 0.02; // 轻微重力
      p.life -= p.decay;
      p.radius *= 0.98;

      if (p.life <= 0 || p.radius < 0.2) {
        trailParticles.splice(i, 1);
        continue;
      }

      // 发光粒子
      const gradient = trailCtx.createRadialGradient(p.x, p.y, 0, p.x, p.y, p.radius * 3);
      gradient.addColorStop(0, p.color + (p.life * 0.9) + ')');
      gradient.addColorStop(0.4, p.color + (p.life * 0.4) + ')');
      gradient.addColorStop(1, p.color + '0)');

      trailCtx.beginPath();
      trailCtx.arc(p.x, p.y, p.radius * 3, 0, Math.PI * 2);
      trailCtx.fillStyle = gradient;
      trailCtx.fill();

      // 核心亮点
      trailCtx.beginPath();
      trailCtx.arc(p.x, p.y, p.radius * 0.5, 0, Math.PI * 2);
      trailCtx.fillStyle = 'rgba(255, 255, 255, ' + (p.life * 0.8) + ')';
      trailCtx.fill();
    }

    requestAnimationFrame(animateTrail);
  }
  animateTrail();

  // ==========================================
  // 2. 网格翻砖滚动过渡（canvas）
  // ==========================================
  const gridCanvas = document.getElementById('gridCanvas');
  const gridCtx = gridCanvas.getContext('2d');
  const sectionList = document.querySelectorAll('section');

  // 浅色主题各 section 的颜色
  const themeColors = [
    { bg: '#f8f9fc', grid: 'rgba(109, 40, 217, 0.07)', accent: '#8b5cf6' },   // Hero - 紫
    { bg: '#f5f9fb', grid: 'rgba(8, 145, 178, 0.07)', accent: '#06b6d4' },   // About - 青
    { bg: '#faf6fc', grid: 'rgba(219, 39, 119, 0.06)', accent: '#ec4899' },  // Skills - 粉
    { bg: '#f6f8fc', grid: 'rgba(37, 99, 235, 0.07)', accent: '#3b82f6' },  // Projects - 蓝
    { bg: '#fcf9f5', grid: 'rgba(217, 119, 6, 0.06)', accent: '#f59e0b' },  // Ideas - 橙
    { bg: '#f5faf7', grid: 'rgba(5, 150, 105, 0.06)', accent: '#10b981' },  // Notes - 绿
    { bg: '#f8f9fc', grid: 'rgba(109, 40, 217, 0.07)', accent: '#8b5cf6' }  // Contact - 紫
  ];

  const TILE_SIZE = 6; // 网格块大小（更细密）
  let gridCols = 0, gridRows = 0;
  let tiles = []; // 每个方块的状态
  let currentThemeIdx = 0;
  let nextThemeIdx = 0;

  // 给每个 section 注入光晕元素
  sectionList.forEach((section) => {
    const glow1 = document.createElement('div');
    glow1.className = 'section-glow glow-1';
    const glow2 = document.createElement('div');
    glow2.className = 'section-glow glow-2';
    section.insertBefore(glow1, section.firstChild);
    section.insertBefore(glow2, section.firstChild);
  });

  function resizeGridCanvas() {
    const dpr = window.devicePixelRatio || 1;
    gridCanvas.width = window.innerWidth * dpr;
    gridCanvas.height = window.innerHeight * dpr;
    gridCanvas.style.width = window.innerWidth + 'px';
    gridCanvas.style.height = window.innerHeight + 'px';
    gridCtx.scale(dpr, dpr);

    gridCols = Math.ceil(window.innerWidth / TILE_SIZE) + 2;
    gridRows = Math.ceil(window.innerHeight / TILE_SIZE) + 2;

    // 初始化所有方块
    tiles = [];
    for (let r = 0; r < gridRows; r++) {
      tiles[r] = [];
      for (let c = 0; c < gridCols; c++) {
        tiles[r][c] = {
          flipProgress: 0,  // 0 = 当前色, 1 = 新色
          flipping: false,
          delay: 0
        };
      }
    }
  }
  resizeGridCanvas();
  window.addEventListener('resize', resizeGridCanvas);

  // hex 转 rgba
  function hexToRgba(hex, alpha) {
    const r = parseInt(hex.slice(1, 3), 16);
    const g = parseInt(hex.slice(3, 5), 16);
    const b = parseInt(hex.slice(5, 7), 16);
    return `rgba(${r}, ${g}, ${b}, ${alpha})`;
  }

  // 颜色插值
  function lerpColor(color1, color2, t) {
    // 解析 rgba
    const parse = (c) => {
      const m = c.match(/rgba?\((\d+),\s*(\d+),\s*(\d+)(?:,\s*([\d.]+))?\)/);
      if (m) {
        return [parseInt(m[1]), parseInt(m[2]), parseInt(m[3]), parseFloat(m[4] || 1)];
      }
      return [0, 0, 0, 1];
    };
    const [r1, g1, b1, a1] = parse(color1);
    const [r2, g2, b2, a2] = parse(color2);
    const r = Math.round(r1 + (r2 - r1) * t);
    const g = Math.round(g1 + (g2 - g1) * t);
    const b = Math.round(b1 + (b2 - b1) * t);
    const a = (a1 + (a2 - a1) * t).toFixed(3);
    return `rgba(${r}, ${g}, ${b}, ${a})`;
  }

  // 计算两个 section 之间的滚动进度 (0-1)
  function getScrollProgress() {
    const scrollY = window.scrollY;
    const viewportH = window.innerHeight;

    // 找到当前跨越的边界
    for (let i = 0; i < sectionList.length - 1; i++) {
      const sectionTop = sectionList[i].offsetTop;
      const sectionBottom = sectionTop + sectionList[i].offsetHeight;
      const nextSectionTop = sectionList[i + 1].offsetTop;
      const nextSectionBottom = nextSectionTop + sectionList[i + 1].offsetHeight;

      // 当视窗中间在两个 section 之间时
      const midPoint = scrollY + viewportH * 0.5;
      const boundary = nextSectionTop;

      // 以边界为中心，前后各半屏作为过渡区域
      const transitionZone = viewportH * 0.8;
      const start = boundary - transitionZone * 0.5;
      const end = boundary + transitionZone * 0.5;

      if (midPoint >= start && midPoint <= end) {
        const progress = (midPoint - start) / (end - start);
        return {
          fromIdx: i,
          toIdx: i + 1,
          progress: Math.max(0, Math.min(1, progress))
        };
      }
    }

    // 不在过渡区域，返回当前所在 section
    let currentIdx = 0;
    const midPoint = scrollY + viewportH * 0.5;
    for (let i = 0; i < sectionList.length; i++) {
      const top = sectionList[i].offsetTop;
      const bottom = top + sectionList[i].offsetHeight;
      if (midPoint >= top && midPoint < bottom) {
        currentIdx = i;
        break;
      }
    }
    return { fromIdx: currentIdx, toIdx: currentIdx, progress: 0 };
  }

  // 触发翻砖动画
  let lastFromIdx = 0;
  let lastToIdx = 0;
  let lastProgress = 0;

  function updateGridFlip() {
    const { fromIdx, toIdx, progress } = getScrollProgress();

    // 如果跨越了新的边界，重置所有方块
    if (fromIdx !== lastFromIdx || toIdx !== lastToIdx) {
      lastFromIdx = fromIdx;
      lastToIdx = toIdx;

      // 如果是同一个 section，全部重置为 0
      if (fromIdx === toIdx) {
        for (let r = 0; r < gridRows; r++) {
          for (let c = 0; c < gridCols; c++) {
            tiles[r][c].flipProgress = 0;
            tiles[r][c].flipping = false;
          }
        }
        currentThemeIdx = fromIdx;
        nextThemeIdx = fromIdx;
        document.body.style.backgroundColor = themeColors[fromIdx].bg;
      } else {
         // 新的过渡开始，计算每块的延迟（从上到下波浪式）
         const dir = toIdx > fromIdx ? 1 : -1;
         for (let r = 0; r < gridRows; r++) {
           for (let c = 0; c < gridCols; c++) {
             // 从上往下按行分布延迟，每列加一点随机偏移
             const normalizedRow = dir > 0 ? r / gridRows : (gridRows - r) / gridRows;
             tiles[r][c].delay = normalizedRow * 0.5 + Math.random() * 0.12;
             tiles[r][c].flipping = false;
             // 如果往回滚，重置进度
             if (dir < 0 && tiles[r][c].flipProgress > 0.5) {
               tiles[r][c].flipProgress = 1 - tiles[r][c].flipProgress;
             }
           }
         }
         currentThemeIdx = fromIdx;
         nextThemeIdx = toIdx;
       }
    }

    lastProgress = progress;

    // 更新每块的翻转进度
    if (fromIdx !== toIdx) {
      for (let r = 0; r < gridRows; r++) {
        for (let c = 0; c < gridCols; c++) {
          const tile = tiles[r][c];
          const effectiveProgress = Math.max(0, Math.min(1, (progress - tile.delay) / 0.4));
          tile.flipProgress = effectiveProgress;
        }
      }

      // body 背景色在进度 50% 左右切换
      if (progress > 0.5) {
        document.body.style.backgroundColor = themeColors[toIdx].bg;
      } else {
        document.body.style.backgroundColor = themeColors[fromIdx].bg;
      }
    }
  }

  // 绘制网格
  function drawGrid() {
    const W = window.innerWidth;
    const H = window.innerHeight;
    gridCtx.clearRect(0, 0, W, H);

    const fromColor = themeColors[currentThemeIdx]?.grid || 'rgba(109, 40, 217, 0.07)';
    const toColor = themeColors[nextThemeIdx]?.grid || 'rgba(109, 40, 217, 0.07)';
    const fromAccent = themeColors[currentThemeIdx]?.accent || '#8b5cf6';
    const toAccent = themeColors[nextThemeIdx]?.accent || '#8b5cf6';

    for (let r = 0; r < gridRows; r++) {
      for (let c = 0; c < gridCols; c++) {
        const x = c * TILE_SIZE;
        const y = r * TILE_SIZE;
        const tile = tiles[r][c];
        const p = tile.flipProgress;

        // 方块的翻转效果：用缩放模拟垂直翻转（上下翻）
        // 进度 0-0.5: 正面缩窄，0.5-1: 背面展开
        let scaleY = 1;
        let color;

        if (p < 0.5) {
          // 前半段：从当前色翻到边缘
          scaleY = 1 - p * 1.6;
          color = fromColor;
        } else {
          // 后半段：从边缘展开到新色
          scaleY = (p - 0.5) * 1.6 + 0.2;
          color = toColor;
        }

        scaleY = Math.max(0.05, Math.min(1, scaleY));

        const drawH = TILE_SIZE * scaleY;
        const drawY = y + (TILE_SIZE - drawH) / 2;

        // 翻转中的方块，填充一点颜色增加立体感
        if (p > 0 && p < 1) {
          gridCtx.fillStyle = color.replace(/[\d.]+\)$/, (parseFloat(color.match(/[\d.]+\)$/)?.[0] || 0.07) * 1.5).toFixed(3) + ')');
          gridCtx.fillRect(x + 0.5, drawY + 0.5, TILE_SIZE - 1, drawH - 1);
        }

        // 网格线（四边）— 细线更细腻
        gridCtx.strokeStyle = color;
        gridCtx.lineWidth = 0.3;
        gridCtx.strokeRect(x + 0.15, drawY + 0.15, TILE_SIZE - 0.3, drawH - 0.3);
      }
    }

    // 径向淡出（让网格从中心向边缘逐渐消失）
    const gradient = gridCtx.createRadialGradient(
      W / 2, H / 2, Math.min(W, H) * 0.25,
      W / 2, H / 2, Math.max(W, H) * 0.65
    );
    gradient.addColorStop(0, 'rgba(0,0,0,0)');
    gradient.addColorStop(1, themeColors[currentThemeIdx]?.bg || '#f8f9fc');

    requestAnimationFrame(drawGrid);
  }
  drawGrid();

  // 滚动监听
  let scrollThrottle = false;
  window.addEventListener('scroll', () => {
    if (!scrollThrottle) {
      scrollThrottle = true;
      requestAnimationFrame(() => {
        updateGridFlip();
        scrollThrottle = false;
      });
    }
  }, { passive: true });

  // 初始化 body 背景
  document.body.style.backgroundColor = themeColors[0].bg;

  // ==========================================
  // 3. 粒子背景
  // ==========================================
  const canvas = document.getElementById('particleCanvas');
  const ctx = canvas.getContext('2d');
  let particles = [];
  let W = 0, H = 0;

  function resizeCanvas() {
    W = canvas.width = window.innerWidth;
    H = canvas.height = window.innerHeight;
    createParticles();
  }

  function createParticles() {
    particles = [];
    const count = Math.floor((W * H) / 18000);
    for (let i = 0; i < count; i++) {
      particles.push({
        x: Math.random() * W,
        y: Math.random() * H,
        vx: (Math.random() - 0.5) * 0.25,
        vy: (Math.random() - 0.5) * 0.25,
        radius: Math.random() * 1.2 + 0.4,
        opacity: Math.random() * 0.4 + 0.15
      });
    }
  }

  function drawParticles() {
    ctx.clearRect(0, 0, W, H);

    // 粒子
    for (let i = 0; i < particles.length; i++) {
      const p = particles[i];
      p.x += p.vx;
      p.y += p.vy;

      if (p.x < 0) p.x = W;
      if (p.x > W) p.x = 0;
      if (p.y < 0) p.y = H;
      if (p.y > H) p.y = 0;

      // 鼠标引力
      const dx = mouseX - p.x;
      const dy = mouseY - p.y;
      const dist = Math.sqrt(dx * dx + dy * dy);
      if (dist < 120) {
        const force = (120 - dist) / 120 * 0.015;
        p.vx += (dx / dist) * force;
        p.vy += (dy / dist) * force;
      }

      // 速度衰减
      p.vx *= 0.99;
      p.vy *= 0.99;

      ctx.beginPath();
      ctx.arc(p.x, p.y, p.radius, 0, Math.PI * 2);
      ctx.fillStyle = `rgba(109, 40, 217, ${p.opacity * 0.5})`;
      ctx.fill();
    }

    // 连线
    for (let i = 0; i < particles.length; i++) {
      for (let j = i + 1; j < particles.length; j++) {
        const dx = particles[i].x - particles[j].x;
        const dy = particles[i].y - particles[j].y;
        const dist = Math.sqrt(dx * dx + dy * dy);
        if (dist < 100) {
          const opacity = (1 - dist / 100) * 0.15;
          ctx.beginPath();
          ctx.moveTo(particles[i].x, particles[i].y);
          ctx.lineTo(particles[j].x, particles[j].y);
          ctx.strokeStyle = `rgba(109, 40, 217, ${opacity * 0.4})`;
          ctx.lineWidth = 0.5;
          ctx.stroke();
        }
      }
    }

    requestAnimationFrame(drawParticles);
  }

  resizeCanvas();
  drawParticles();
  window.addEventListener('resize', resizeCanvas);

  // ==========================================
  // 4. 滚动进度条
  // ==========================================
  const progressBar = document.createElement('div');
  progressBar.className = 'scroll-progress';
  document.body.appendChild(progressBar);

  window.addEventListener('scroll', () => {
    const scrollTop = window.scrollY;
    const docHeight = document.documentElement.scrollHeight - window.innerHeight;
    const progress = (scrollTop / docHeight) * 100;
    progressBar.style.width = progress + '%';
  }, { passive: true });

  // ==========================================
  // 5. 导航栏滚动效果
  // ==========================================
  const navbar = document.querySelector('.navbar');
  const navLinks = document.querySelectorAll('.nav-link');
  const navToggle = document.querySelector('.nav-toggle');
  const navMenu = document.querySelector('.nav-menu');

  window.addEventListener('scroll', () => {
    if (window.scrollY > 50) {
      navbar.classList.add('scrolled');
    } else {
      navbar.classList.remove('scrolled');
    }

    // 导航高亮
    const scrollPos = window.scrollY + 120;
    let currentSection = '';

    sectionList.forEach(section => {
      const top = section.offsetTop;
      const height = section.offsetHeight;
      if (scrollPos >= top && scrollPos < top + height) {
        currentSection = section.getAttribute('id');
      }
    });

    navLinks.forEach(link => {
      link.classList.remove('active');
      if (link.getAttribute('href') === '#' + currentSection) {
        link.classList.add('active');
      }
    });
  }, { passive: true });

  // 移动端菜单
  if (navToggle) {
    navToggle.addEventListener('click', () => {
      navToggle.classList.toggle('active');
      navMenu.classList.toggle('open');
    });

    navLinks.forEach(link => {
      link.addEventListener('click', () => {
        navToggle.classList.remove('active');
        navMenu.classList.remove('open');
      });
    });
  }

  // ==========================================
  // 6. 滚动显示动画 (IntersectionObserver)
  // ==========================================
  const revealElements = document.querySelectorAll('.reveal');
  const levelBars = document.querySelectorAll('.level-bar');

  const revealObserver = new IntersectionObserver((entries) => {
    entries.forEach(entry => {
      if (entry.isIntersecting) {
        entry.target.classList.add('visible');

        // 技能条动画
        if (entry.target.classList.contains('bento-large')) {
          const bar = entry.target.querySelector('.level-bar');
          if (bar) {
            const targetWidth = bar.style.width;
            bar.style.width = '0';
            setTimeout(() => {
              bar.style.width = targetWidth;
            }, 200);
          }
        }
      }
    });
  }, {
    threshold: 0.1,
    rootMargin: '0px 0px -60px 0px'
  });

  revealElements.forEach(el => revealObserver.observe(el));

  // ==========================================
  // 7. 3D 卡片倾斜效果
  // ==========================================
  const tiltCards = document.querySelectorAll('.tilt-card, .project-card, .idea-card, .note-card, .contact-item');

  tiltCards.forEach(card => {
    card.addEventListener('mousemove', (e) => {
      const rect = card.getBoundingClientRect();
      const x = e.clientX - rect.left;
      const y = e.clientY - rect.top;
      const centerX = rect.width / 2;
      const centerY = rect.height / 2;
      const rotateX = (y - centerY) / 25;
      const rotateY = (centerX - x) / 25;

      card.style.transform = `perspective(1000px) rotateX(${rotateX}deg) rotateY(${rotateY}deg) translateY(-6px) scale(1.015)`;
    });

    card.addEventListener('mouseleave', () => {
      card.style.transform = '';
    });
  });

  // ==========================================
  // 8. 项目筛选
  // ==========================================
  const filterBtns = document.querySelectorAll('.filter-btn');
  const projectCards = document.querySelectorAll('.project-card');

  filterBtns.forEach(btn => {
    btn.addEventListener('click', () => {
      filterBtns.forEach(b => b.classList.remove('active'));
      btn.classList.add('active');

      const filter = btn.getAttribute('data-filter');

      projectCards.forEach(card => {
        const type = card.getAttribute('data-type');
        if (filter === 'all' || filter === type) {
          card.classList.remove('hidden');
          card.style.animation = 'fadeInUp 0.5s ease both';
        } else {
          card.classList.add('hidden');
        }
      });
    });
  });

  // ==========================================
  // 9. 数字计数动画
  // ==========================================
  const counters = document.querySelectorAll('.mini-num');

  function animateCounter(el) {
    const target = parseInt(el.getAttribute('data-target') || el.textContent);
    const duration = 1800;
    const start = performance.now();

    function step(now) {
      const progress = Math.min((now - start) / duration, 1);
      const eased = 1 - Math.pow(1 - progress, 3);
      const current = Math.floor(eased * target);
      el.textContent = current + (el.getAttribute('data-suffix') || '');
      if (progress < 1) requestAnimationFrame(step);
    }
    requestAnimationFrame(step);
  }

  const counterObserver = new IntersectionObserver((entries) => {
    entries.forEach(entry => {
      if (entry.isIntersecting) {
        const stats = entry.target.querySelectorAll('.mini-num');
        stats.forEach(s => animateCounter(s));
        counterObserver.unobserve(entry.target);
      }
    });
  }, { threshold: 0.5 });

  const statsRow = document.querySelector('.hero-stats-row');
  if (statsRow) counterObserver.observe(statsRow);

  // ==========================================
  // 10. Hero 视差效果
  // ==========================================
  const heroOrb = document.querySelector('.hero-orb');
  const floatTags = document.querySelectorAll('.float-tag');
  const heroGlows = document.querySelectorAll('.hero-glow');

  document.addEventListener('mousemove', (e) => {
    const x = (e.clientX / window.innerWidth - 0.5) * 2;
    const y = (e.clientY / window.innerHeight - 0.5) * 2;

    if (heroOrb) {
      heroOrb.style.transform = `translate(${x * 20}px, ${y * 20}px)`;
    }

    floatTags.forEach((tag, i) => {
      const factor = (i + 1) * 6;
      tag.style.transform = `translate(${x * factor}px, ${y * factor}px)`;
    });

    heroGlows.forEach((glow, i) => {
      const factor = (i + 1) * 15;
      glow.style.transform = `translate(${x * factor}px, ${y * factor}px)`;
    });
  });

  // ==========================================
  // 11. 回到顶部
  // ==========================================
  const backToTop = document.querySelector('.back-to-top');

  window.addEventListener('scroll', () => {
    if (window.scrollY > 500) {
      backToTop.classList.add('visible');
    } else {
      backToTop.classList.remove('visible');
    }
  }, { passive: true });

  if (backToTop) {
    backToTop.addEventListener('click', () => {
      window.scrollTo({ top: 0, behavior: 'smooth' });
    });
  }

  // ==========================================
  // 12. 表单提交
  // ==========================================
  const contactForm = document.querySelector('.contact-form form');
  if (contactForm) {
    contactForm.addEventListener('submit', (e) => {
      e.preventDefault();
      const btn = contactForm.querySelector('button[type="submit"]');
      const originalText = btn.innerHTML;
      btn.innerHTML = '<span class="btn-text-deco">[</span>发送中...<span class="btn-text-deco">]</span>';
      btn.disabled = true;

      setTimeout(() => {
        btn.innerHTML = '<span class="btn-text-deco">[</span>已收到！<span class="btn-arrow">✓</span><span class="btn-text-deco">]</span>';
        btn.style.background = 'var(--gradient-3)';

        setTimeout(() => {
          btn.innerHTML = originalText;
          btn.disabled = false;
          btn.style.background = '';
          contactForm.reset();
        }, 2500);
      }, 1200);
    });
  }

  // ==========================================
  // 13. 平滑滚动
  // ==========================================
  document.querySelectorAll('a[href^="#"]').forEach(anchor => {
    anchor.addEventListener('click', function (e) {
      e.preventDefault();
      const href = this.getAttribute('href');
      const target = document.querySelector(href);
      if (target) {
        target.scrollIntoView({
          behavior: 'smooth',
          block: 'start'
        });
      }
    });
  });

  // ==========================================
  // 14. 中英文切换
  // ==========================================
  const i18n = {
    zh: {
      'nav.about': '概览',
      'nav.skills': '方向',
      'nav.projects': '项目',
      'nav.ideas': '创意',
      'nav.notes': '研究',
      'nav.contact': '交流',
      'visit.total': '总访问',
      'visit.last': '最近',
      'visit.online': '在线',
      'hero.tag': 'CREATIVE RESEARCH LAB / 创意研究实验室',
      'hero.line1': '探索',
      'hero.line2': '创意与设计',
      'hero.line3': '的边界',
      'hero.desc': '一个面向创意与技术的开放实验平台 —— 聚焦 AI 探索、创意设计、数据洞察、全栈开发、交互体验、硬件创新与游戏实验。<br/>在这里，想法被验证，原型被构建，边界被推动。',
      'hero.btn1': '浏览创意项目',
      'hero.btn2.sub': '前沿想法',
      'hero.stat1.label': '创意项目',
      'hero.stat2.label': '研究笔记',
      'hero.stat3.label': '开源仓库',
      'hero.stat4.label': '探索方向',
      'skills.title.p1': '研究',
      'skills.title.p2': '方向',
      'skills.subtitle': '从人工智能到硬件创新，跨学科探索，持续扩展中...',
      'projects.title.p1': '创意',
      'projects.title.p2': '项目',
      'projects.subtitle': '跨越多个领域的实验项目与开源作品',
      'filter.all': '全部',
      'filter.mobile': '移动端',
      'ideas.title.p1': '前沿',
      'ideas.title.p2': '创意',
      'ideas.title.p3': '探索',
      'ideas.subtitle': '待验证的假设、跨学科的思考、以及对未来技术的展望。欢迎参与讨论！',
      'notes.title.p1': '研究',
      'notes.title.p2': '笔记',
      'notes.subtitle': '技术洞察、算法推导、设计思考与研究总结',
      'contact.title.p1': '提交与',
      'contact.title.p2': '交流',
      'contact.desc': '有创意想法想要落地？对某个方向有独到见解？欢迎提交与交流，我们相信好的想法值得被实现。',
      'footer.desc': '一个面向创意与技术的开放研究平台，持续探索算法、设计与创新的边界。',
      'footer.col1': '导航',
      'footer.col2': '资源',
      'footer.col3': '交流',
      'footer.copyright': '© 2025 Creative Research Lab. All rights reserved.',
      'footer.motto': '探索不止，创新不息。',
      'form.nameLabel': '姓名',
      'form.name': '你的名字',
      'form.emailLabel': '邮箱',
      'form.subjectLabel': '主题',
      'form.subject': '想聊点什么？',
      'form.messageLabel': '内容',
      'form.message': '随便说点什么...',
      'form.submit': '提交消息',
      'help.title': '关于本站',
      'help.what.title': '这是什么？',
      'help.what.desc': '一个面向创意与技术的开放研究平台，聚焦 AI 探索、算法设计、数据洞察、全栈开发、交互设计、硬件创新与游戏实验。',
      'help.features.title': '核心内容',
      'help.features.1': '🧠 AI 探索与算法研究',
      'help.features.2': '📊 数据科学与可视化',
      'help.features.3': '💻 全栈开发与工程实践',
      'help.features.4': '🎨 交互设计与创意实验',
      'help.features.5': '🔌 硬件创新与物联网',
      'help.features.6': '🎮 游戏开发与交互艺术',
      'help.features.7': '📚 技术研究笔记与文献',
      'help.features.8': '💡 前沿想法与未来展望',
      'help.usage.title': '如何使用',
      'help.usage.1': '🖱 滚动页面浏览各板块内容',
      'help.usage.2': '🌐 点击右上角「中 / EN」切换语言',
      'help.usage.3': '📬 有想法？通过「提交与交流」板块发送',
      'help.usage.4': '⚡ 滚动时可观察网格翻砖过渡特效',
      'help.contact.title': '联系方式'
    },
    en: {
      'nav.about': 'Overview',
      'nav.skills': 'Focus',
      'nav.projects': 'Projects',
      'nav.ideas': 'Ideas',
      'nav.notes': 'Research',
      'nav.contact': 'Connect',
      'visit.total': 'Visits',
      'visit.last': 'Last',
      'visit.online': 'Online',
      'hero.tag': 'CREATIVE RESEARCH LAB',
      'hero.line1': 'Exploring',
      'hero.line2': 'the edge of',
      'hero.line3': 'ideas & design',
      'hero.desc': 'An open experimental platform for creativity and technology — focused on AI exploration, creative design, data insights, full-stack development, interaction experience, hardware innovation and game experiments.<br/>Where ideas are validated, prototypes are built, and boundaries are pushed.',
      'hero.btn1': 'Explore Projects',
      'hero.btn2.sub': 'Frontier Ideas',
      'hero.stat1.label': 'Projects',
      'hero.stat2.label': 'Papers',
      'hero.stat3.label': 'Repos',
      'hero.stat4.label': 'Directions',
      'skills.title.p1': 'Research',
      'skills.title.p2': 'Areas',
      'skills.subtitle': 'From AI to hardware innovation — interdisciplinary exploration',
      'projects.title.p1': 'Creative',
      'projects.title.p2': 'Projects',
      'projects.subtitle': 'Experimental projects and open-source works across disciplines',
      'filter.all': 'All',
      'filter.mobile': 'Mobile',
      'ideas.title.p1': 'Frontier',
      'ideas.title.p2': 'Ideas',
      'ideas.title.p3': '& Vision',
      'ideas.subtitle': 'Hypotheses to validate, interdisciplinary thinking, and visions for future tech.',
      'notes.title.p1': 'Research',
      'notes.title.p2': 'Notes',
      'notes.subtitle': 'Technical insights, algorithm derivations, and design reflections',
      'contact.title.p1': 'Submit &',
      'contact.title.p2': 'Connect',
      'contact.desc': 'Have a creative idea to build? A unique perspective to share? We believe good ideas deserve to be realized.',
      'footer.desc': 'An open research platform for creativity and technology — pushing the boundaries of algorithms, design and innovation.',
      'footer.col1': 'Navigate',
      'footer.col2': 'Resources',
      'footer.col3': 'Connect',
      'footer.copyright': '© 2025 Creative Research Lab. All rights reserved.',
      'footer.motto': 'Explore endlessly, innovate ceaselessly.',
      'form.nameLabel': 'Name',
      'form.name': 'Your name',
      'form.emailLabel': 'Email',
      'form.subjectLabel': 'Subject',
      'form.subject': 'What would you like to share?',
      'form.messageLabel': 'Message',
      'form.message': 'Share your thoughts...',
      'form.submit': 'Submit',
      'help.title': 'About This Site',
      'help.what.title': 'What is this?',
      'help.what.desc': 'An open research platform for creativity and technology — focused on AI exploration, algorithm design, data insights, full-stack development, interaction design, hardware innovation and game experiments.',
      'help.features.title': 'Core Areas',
      'help.features.1': '🧠 AI Research & Algorithm Design',
      'help.features.2': '📊 Data Science & Visualization',
      'help.features.3': '💻 Full-Stack Development',
      'help.features.4': '🎨 Interaction Design & Creative Experiments',
      'help.features.5': '🔌 Hardware Innovation & IoT',
      'help.features.6': '🎮 Game Dev & Interactive Art',
      'help.features.7': '📚 Research Notes & Papers',
      'help.features.8': '💡 Frontier Ideas & Future Vision',
      'help.usage.title': 'How to Use',
      'help.usage.1': '🖱 Scroll to explore different sections',
      'help.usage.2': '🌐 Click "中 / EN" in the top-right to switch language',
      'help.usage.3': '📬 Submit ideas via the "Submit & Connect" section',
      'help.usage.4': '⚡ Watch for the grid tile transition when scrolling',
      'help.contact.title': 'Contact'
    }
  };

  let currentLang = localStorage.getItem('ycc-lang') || 'zh';

  function applyLang(lang) {
    currentLang = lang;
    localStorage.setItem('ycc-lang', lang);
    const dict = i18n[lang];
    // 文本内容
    document.querySelectorAll('[data-i18n]').forEach(el => {
      const key = el.getAttribute('data-i18n');
      if (dict[key]) {
        el.innerHTML = dict[key];
      }
    });
    // placeholder
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
      const key = el.getAttribute('data-i18n-placeholder');
      if (dict[key]) {
        el.placeholder = dict[key];
      }
    });
    // 更新语言按钮状态
    const langToggle = document.getElementById('langToggle');
    if (langToggle) {
      langToggle.querySelector('.lang-cn').classList.toggle('active', lang === 'zh');
      langToggle.querySelector('.lang-en').classList.toggle('active', lang === 'en');
    }
  }

  const langToggle = document.getElementById('langToggle');
  if (langToggle) {
    langToggle.addEventListener('click', () => {
      const newLang = currentLang === 'zh' ? 'en' : 'zh';
      applyLang(newLang);
    });
  }

  // 初始化语言
  applyLang(currentLang);

  // ==========================================
  // 15. 访问统计
  // ==========================================
  function updateVisitStats() {
    const VISIT_KEY = 'ycc_visit_stats';
    let stats = JSON.parse(localStorage.getItem(VISIT_KEY) || '{}');

    // 初始化
    if (!stats.total) {
      stats = {
        total: Math.floor(Math.random() * 500) + 1200, // 初始基数
        lastVisit: Date.now(),
        online: 1
      };
    }

    // 新的一次访问（距离上次超过 30 分钟算一次新访问）
    const now = Date.now();
    if (now - stats.lastVisit > 30 * 60 * 1000) {
      stats.total += 1;
    }
    stats.lastVisit = now;
    localStorage.setItem(VISIT_KEY, JSON.stringify(stats));

    // 更新显示
    const totalEl = document.getElementById('visitTotal');
    const lastEl = document.getElementById('visitLast');
    const onlineEl = document.getElementById('visitOnline');

    if (totalEl) {
      animateNumber(totalEl, stats.total);
    }
    if (lastEl) {
      const d = new Date(stats.lastVisit);
      const pad = n => n.toString().padStart(2, '0');
      lastEl.textContent = `${pad(d.getMonth()+1)}/${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`;
    }
    if (onlineEl) {
      // 模拟在线人数：1-3 人
      const online = Math.floor(Math.random() * 3) + 1;
      onlineEl.textContent = online;
    }
  }

  function animateNumber(el, target) {
    const start = parseInt(el.textContent) || 0;
    const duration = 1500;
    const startTime = performance.now();

    function step(currentTime) {
      const elapsed = currentTime - startTime;
      const progress = Math.min(elapsed / duration, 1);
      const eased = 1 - Math.pow(1 - progress, 3);
      const current = Math.floor(start + (target - start) * eased);
      el.textContent = current.toLocaleString();
      if (progress < 1) {
        requestAnimationFrame(step);
      }
    }
    requestAnimationFrame(step);
  }

  updateVisitStats();

  // ==========================================
  // 16. 帮助弹窗
  // ==========================================
  const helpBtn = document.getElementById('helpBtn');
  const helpModal = document.getElementById('helpModal');
  const helpModalClose = document.getElementById('helpModalClose');
  const helpModalOverlay = document.getElementById('helpModalOverlay');

  function openHelpModal() {
    if (helpModal) {
      helpModal.classList.add('active');
      document.body.style.overflow = 'hidden';
    }
  }

  function closeHelpModal() {
    if (helpModal) {
      helpModal.classList.remove('active');
      document.body.style.overflow = '';
    }
  }

  if (helpBtn) helpBtn.addEventListener('click', openHelpModal);
  if (helpModalClose) helpModalClose.addEventListener('click', closeHelpModal);
  if (helpModalOverlay) helpModalOverlay.addEventListener('click', closeHelpModal);

  // ESC 关闭
  document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape' && helpModal?.classList.contains('active')) {
      closeHelpModal();
    }
  });

  // ==========================================
  // 17. 左侧悬浮飘动标签
  // ==========================================
  const tagsCanvas = document.getElementById('floatTagsCanvas');
  if (tagsCanvas) {
    const tagsCtx = tagsCanvas.getContext('2d');

    // 关键词标签库（6 大类，80+ 词）
    const tagPool = [
      // —— AI / 机器学习 ——
      { text: 'AI', size: 'xl', category: 'ai' },
      { text: '深度学习', size: 'xl', category: 'ai' },
      { text: '大语言模型', size: 'lg', category: 'ai' },
      { text: '计算机视觉', size: 'lg', category: 'ai' },
      { text: '神经网络', size: 'md', category: 'ai' },
      { text: 'Transformer', size: 'md', category: 'ai' },
      { text: '扩散模型', size: 'md', category: 'ai' },
      { text: '强化学习', size: 'md', category: 'ai' },
      { text: 'Agent 智能体', size: 'lg', category: 'ai' },
      { text: '知识库', size: 'md', category: 'ai' },
      { text: 'RAG 检索', size: 'md', category: 'ai' },
      { text: '多模态', size: 'md', category: 'ai' },
      { text: 'Prompt 工程', size: 'md', category: 'ai' },
      { text: '模型微调', size: 'sm', category: 'ai' },
      { text: '语义理解', size: 'sm', category: 'ai' },
      { text: '图像生成', size: 'sm', category: 'ai' },
      { text: '语音识别', size: 'sm', category: 'ai' },
      { text: '机器翻译', size: 'sm', category: 'ai' },
      { text: '风格迁移', size: 'sm', category: 'ai' },
      { text: '目标检测', size: 'sm', category: 'ai' },

      // —— 算法 / 数据 ——
      { text: '算法设计', size: 'lg', category: 'algo' },
      { text: '分类', size: 'sm', category: 'algo' },
      { text: '聚类', size: 'sm', category: 'algo' },
      { text: '预测', size: 'sm', category: 'algo' },
      { text: '规划', size: 'sm', category: 'algo' },
      { text: '大数据', size: 'lg', category: 'algo' },
      { text: '数据挖掘', size: 'md', category: 'algo' },
      { text: '数据分析', size: 'md', category: 'algo' },
      { text: '可视化', size: 'md', category: 'algo' },
      { text: '爬虫', size: 'sm', category: 'algo' },
      { text: '数据库', size: 'sm', category: 'algo' },
      { text: '数据结构', size: 'sm', category: 'algo' },
      { text: '数学建模', size: 'md', category: 'algo' },
      { text: '概率论', size: 'sm', category: 'algo' },
      { text: '图论', size: 'sm', category: 'algo' },
      { text: '运筹优化', size: 'sm', category: 'algo' },
      { text: '统计学习', size: 'sm', category: 'algo' },
      { text: '特征工程', size: 'sm', category: 'algo' },

      // —— 开发 / 工程 ——
      { text: '全栈开发', size: 'lg', category: 'dev' },
      { text: '前端', size: 'md', category: 'dev' },
      { text: '后端', size: 'md', category: 'dev' },
      { text: '交互设计', size: 'md', category: 'dev' },
      { text: '架构设计', size: 'md', category: 'dev' },
      { text: '微服务', size: 'sm', category: 'dev' },
      { text: '云原生', size: 'sm', category: 'dev' },
      { text: 'DevOps', size: 'sm', category: 'dev' },
      { text: '开源', size: 'sm', category: 'dev' },
      { text: '性能优化', size: 'sm', category: 'dev' },
      { text: '工程化', size: 'sm', category: 'dev' },
      { text: 'API 设计', size: 'sm', category: 'dev' },
      { text: '测试驱动', size: 'sm', category: 'dev' },
      { text: '代码重构', size: 'sm', category: 'dev' },

      // —— 应用场景 ——
      { text: '智能监控', size: 'md', category: 'app' },
      { text: '健康管理', size: 'md', category: 'app' },
      { text: '远程控制', size: 'sm', category: 'app' },
      { text: '自动驾驶', size: 'md', category: 'app' },
      { text: '智慧医疗', size: 'md', category: 'app' },
      { text: '金融科技', size: 'md', category: 'app' },
      { text: '推荐系统', size: 'sm', category: 'app' },
      { text: '智能客服', size: 'sm', category: 'app' },
      { text: '工业质检', size: 'sm', category: 'app' },
      { text: '智慧城市', size: 'sm', category: 'app' },

      // —— 研究 / 创意 ——
      { text: '论文研读', size: 'md', category: 'research' },
      { text: '创新实验', size: 'md', category: 'research' },
      { text: '前沿探索', size: 'md', category: 'research' },
      { text: '技术展望', size: 'sm', category: 'research' },
      { text: '原型设计', size: 'sm', category: 'research' },
      { text: '创意实现', size: 'lg', category: 'research' },
      { text: '开源贡献', size: 'sm', category: 'research' },
      { text: '技术写作', size: 'sm', category: 'research' },
      { text: '知识沉淀', size: 'sm', category: 'research' },

      // —— 生活 / 兴趣 ——
      { text: '摄影', size: 'lg', category: 'life' },
      { text: '旅行', size: 'lg', category: 'life' },
      { text: '乒乓球', size: 'md', category: 'life' },
      { text: '羽毛球', size: 'md', category: 'life' },
      { text: '跑步', size: 'md', category: 'life' },
      { text: '游泳', size: 'sm', category: 'life' },
      { text: '骑行', size: 'sm', category: 'life' },
      { text: '登山', size: 'sm', category: 'life' },
      { text: '电影', size: 'md', category: 'life' },
      { text: '音乐', size: 'md', category: 'life' },
      { text: '阅读', size: 'md', category: 'life' },
      { text: '写作', size: 'sm', category: 'life' },
      { text: '烹饪', size: 'sm', category: 'life' },
      { text: '手冲咖啡', size: 'sm', category: 'life' },
      { text: '独立游戏', size: 'md', category: 'life' },
      { text: 'RPG', size: 'sm', category: 'life' },
      { text: 'FPS', size: 'sm', category: 'life' },
      { text: 'MOBA', size: 'sm', category: 'life' },
      { text: '策略游戏', size: 'sm', category: 'life' },
      { text: '沙盒游戏', size: 'sm', category: 'life' },
      { text: '开放世界', size: 'sm', category: 'life' },
      { text: '科幻作品', size: 'sm', category: 'life' },
    ];

    // 字号映射（整体放大）
    const sizeMap = { xl: 32, lg: 24, md: 18, sm: 14 };

    let tags = [];
    let tagW = 0, tagH = 0;

    function initTags() {
      const canvas = tagsCanvas;
      tagW = canvas.offsetWidth;
      tagH = canvas.offsetHeight;
      canvas.width = tagW * window.devicePixelRatio;
      canvas.height = tagH * window.devicePixelRatio;
      tagsCtx.scale(window.devicePixelRatio, window.devicePixelRatio);

      // 按尺寸从大到小排序，大的先放
      const sortedTags = [...tagPool].sort((a, b) => {
        const rank = { xl: 4, lg: 3, md: 2, sm: 1 };
        return rank[b.size] - rank[a.size];
      });

      const placed = []; // 已放置的标签 {x, y, w, h}

      tags = sortedTags.map((tag) => {
        const fontSize = sizeMap[tag.size] || 16;
        // 估算标签尺寸（文字宽度）
        const estWidth = fontSize * tag.text.length * 0.7 + 10;
        const estHeight = fontSize * 1.4;

        // 优先区域：大标签左上，小标签右下
        let minX, maxX, minY, maxY;
        if (tag.size === 'xl') {
          minX = 0.05; maxX = 0.4; minY = 0.03; maxY = 0.25;
        } else if (tag.size === 'lg') {
          minX = 0.05; maxX = 0.55; minY = 0.05; maxY = 0.45;
        } else if (tag.size === 'md') {
          minX = 0.08; maxX = 0.75; minY = 0.15; maxY = 0.7;
        } else {
          minX = 0.15; maxX = 0.92; minY = 0.3; maxY = 0.9;
        }

        // 尝试找一个不重叠的位置（最多 80 次）
        let bestX = 0, bestY = 0, bestDist = -1;
        for (let attempt = 0; attempt < 80; attempt++) {
          const tryX = (minX + Math.random() * (maxX - minX)) * tagW;
          const tryY = (minY + Math.random() * (maxY - minY)) * tagH;

          // 检查与已放置标签的距离
          let minDist = Infinity;
          let overlaps = false;
          for (const p of placed) {
            const dx = tryX - p.x;
            const dy = tryY - p.y;
            const dist = Math.sqrt(dx * dx + dy * dy);
            const minSafeDist = (estWidth + p.w) * 0.5 + 8; // 安全距离
            if (dist < minSafeDist) { overlaps = true; break; }
            if (dist < minDist) minDist = dist;
          }

          if (!overlaps) {
            bestX = tryX;
            bestY = tryY;
            break;
          } else if (minDist > bestDist) {
            bestDist = minDist;
            bestX = tryX;
            bestY = tryY;
          }
        }

        // 记录放置位置
        placed.push({ x: bestX, y: bestY, w: estWidth, h: estHeight });

        const baseX = bestX / tagW;
        const baseY = bestY / tagH;

        return {
          text: tag.text,
          category: tag.category,
          fontSize: fontSize,
          size: tag.size,
          baseX: baseX,
          baseY: baseY,
          x: bestX,
          y: bestY,
          // 飘动速度：大的慢，小的稍快
          vx: (Math.random() - 0.5) * (tag.size === 'xl' ? 0.1 : tag.size === 'lg' ? 0.15 : tag.size === 'md' ? 0.22 : 0.3),
          vy: (Math.random() - 0.5) * (tag.size === 'xl' ? 0.06 : tag.size === 'lg' ? 0.1 : tag.size === 'md' ? 0.14 : 0.2),
          phase: Math.random() * Math.PI * 2,
          swaySpeed: 0.002 + Math.random() * 0.005,
          swayAmp: tag.size === 'xl' ? 5 : tag.size === 'lg' ? 7 : tag.size === 'md' ? 9 : 7,
          baseOpacity: tag.size === 'xl' ? 0.85 : tag.size === 'lg' ? 0.72 : tag.size === 'md' ? 0.58 : 0.42,
          rot: (Math.random() - 0.5) * 0.06,
          // 估算尺寸（碰撞用）
          estW: estWidth,
          estH: estHeight,
        };
      });
    }

    function hexToRgb(hex) {
      const m = hex.replace('#', '');
      return {
        r: parseInt(m.substring(0, 2), 16),
        g: parseInt(m.substring(2, 4), 16),
        b: parseInt(m.substring(4, 6), 16)
      };
    }

    function lerpColor(c1, c2, t) {
      return {
        r: Math.round(c1.r + (c2.r - c1.r) * t),
        g: Math.round(c1.g + (c2.g - c1.g) * t),
        b: Math.round(c1.b + (c2.b - c1.b) * t),
      };
    }

    // 获取当前主题色（随滚动变化）
    function getThemeColorForCategory(category, progress) {
      const fromColor = themeColors[currentThemeIdx]?.accent || '#8b5cf6';
      const toColor = themeColors[nextThemeIdx]?.accent || '#8b5cf6';
      const p = progress || 0;

      const fromRgb = hexToRgb(fromColor);
      const toRgb = hexToRgb(toColor);
      const lerped = lerpColor(fromRgb, toRgb, p);

      // 不同分类有不同明暗偏移
      const offsets = { ai: 0, algo: -15, dev: 15, app: -25, research: 25, life: -35 };
      const offset = offsets[category] ?? 0;

      const r = Math.max(0, Math.min(255, lerped.r + offset));
      const g = Math.max(0, Math.min(255, lerped.g + offset * 0.5));
      const b = Math.max(0, Math.min(255, lerped.b + offset * 0.3));

      return { r, g, b };
    }

    function drawTags() {
      tagsCtx.clearRect(0, 0, tagW, tagH);

      const time = performance.now() * 0.001;
      const state = window.scrollThemeState || { fromIdx: 0, toIdx: 0, progress: 0 };

      // 碰撞推开（每帧做轻度分离，防止标签重叠）
      for (let i = 0; i < tags.length; i++) {
        for (let j = i + 1; j < tags.length; j++) {
          const a = tags[i], b = tags[j];
          const dx = b.x - a.x;
          const dy = b.y - a.y;
          const dist = Math.sqrt(dx * dx + dy * dy);
          const minDist = (a.estW + b.estW) * 0.45 + 4; // 最小安全距离

          if (dist < minDist && dist > 0.1) {
            const overlap = (minDist - dist) * 0.15; // 推开力度
            const nx = dx / dist;
            const ny = dy / dist;
            // 大标签推的力度小，小标签被推开
            const ratioA = b.fontSize / (a.fontSize + b.fontSize);
            const ratioB = a.fontSize / (a.fontSize + b.fontSize);
            a.x -= nx * overlap * ratioA;
            a.y -= ny * overlap * ratioA;
            b.x += nx * overlap * ratioB;
            b.y += ny * overlap * ratioB;
            // 交换一点速度方向，增加动感
            const tempVx = a.vx * 0.3;
            a.vx = b.vx * 0.3;
            b.vx = tempVx;
          }
        }
      }

      tags.forEach(tag => {
        tag.x += tag.vx;
        tag.y += tag.vy;

        // 围绕基准点在范围内反弹
        const rangeX = tag.size === 'xl' ? 30 : tag.size === 'lg' ? 45 : tag.size === 'md' ? 55 : 40;
        const rangeY = tag.size === 'xl' ? 20 : tag.size === 'lg' ? 30 : tag.size === 'md' ? 40 : 30;
        const baseX = tag.baseX * tagW;
        const baseY = tag.baseY * tagH;

        if (tag.x < baseX - rangeX || tag.x > baseX + rangeX) tag.vx *= -1;
        if (tag.y < baseY - rangeY || tag.y > baseY + rangeY) tag.vy *= -1;

        // 正弦摆动
        const swayY = Math.sin(time * tag.swaySpeed * 60 + tag.phase) * tag.swayAmp;
        const swayX = Math.cos(time * tag.swaySpeed * 30 + tag.phase * 1.5) * tag.swayAmp * 0.5;

        const drawX = tag.x + swayX;
        const drawY = tag.y + swayY;

        const color = getThemeColorForCategory(tag.category, state.progress);

        // 视口中心附近更亮
        const distFromCenter = Math.abs(drawY - window.innerHeight * 0.5) / (window.innerHeight * 0.5);
        const visibilityBoost = Math.max(0, 1 - distFromCenter * 0.6);
        const finalOpacity = tag.baseOpacity * (0.6 + visibilityBoost * 0.4);

        tagsCtx.save();
        tagsCtx.translate(drawX, drawY);
        tagsCtx.rotate(tag.rot);
        tagsCtx.globalAlpha = finalOpacity;

        tagsCtx.font = `600 ${tag.fontSize}px "Noto Sans SC", "ZCOOL XiaoWei", sans-serif`;
        tagsCtx.textAlign = 'center';
        tagsCtx.textBaseline = 'middle';

        const glowSize = tag.size === 'xl' ? 12 : tag.size === 'lg' ? 8 : tag.size === 'md' ? 5 : 3;
        tagsCtx.shadowColor = `rgba(${color.r}, ${color.g}, ${color.b}, 0.6)`;
        tagsCtx.shadowBlur = glowSize;

        tagsCtx.fillStyle = `rgba(${color.r}, ${color.g}, ${color.b}, 0.95)`;
        tagsCtx.fillText(tag.text, 0, 0);

        tagsCtx.shadowBlur = 0;
        tagsCtx.restore();
      });

      requestAnimationFrame(drawTags);
    }

    initTags();
    drawTags();

    let resizeTimer = null;
    window.addEventListener('resize', () => {
      clearTimeout(resizeTimer);
      resizeTimer = setTimeout(initTags, 300);
    });

    // 同步滚动主题状态
    function updateScrollTheme() {
      window.scrollThemeState = getScrollProgress();
      requestAnimationFrame(updateScrollTheme);
    }
    updateScrollTheme();
  }

  // ==========================================
  // 18. 音乐播放器 + 网格可视化
  // ==========================================
  const musicPlayer = document.getElementById('musicPlayer');
  const musicToggle = document.getElementById('musicToggle');
  const musicPanel = document.getElementById('musicPanel');
  const musicPlayBtn = document.getElementById('musicPlayBtn');
  const bgMusic = document.getElementById('bgMusic');
  const musicProgress = document.getElementById('musicProgress');
  const musicProgressBar = document.getElementById('musicProgressBar');
  const musicProgressThumb = document.getElementById('musicProgressThumb');
  const musicCurrent = document.getElementById('musicCurrent');
  const musicDuration = document.getElementById('musicDuration');
  const volumeSlider = document.getElementById('volumeSlider');
  const volumeBar = document.getElementById('volumeBar');

  let audioCtx = null;
  let analyser = null;
  let sourceNode = null;
  let dataArray = null;
  let bufferLength = 0;
  let musicVisualActive = false;

  // 切换面板展开/收起
  if (musicToggle) {
    musicToggle.addEventListener('click', () => {
      musicPlayer.classList.toggle('open');
    });
  }

  // 初始化音频分析
  function initAudioAnalyser() {
    if (audioCtx) return;
    try {
      audioCtx = new (window.AudioContext || window.webkitAudioContext)();
      analyser = audioCtx.createAnalyser();
      analyser.fftSize = 256;
      bufferLength = analyser.frequencyBinCount;
      dataArray = new Uint8Array(bufferLength);
      sourceNode = audioCtx.createMediaElementSource(bgMusic);
      sourceNode.connect(analyser);
      analyser.connect(audioCtx.destination);
    } catch (e) {
      console.warn('Audio context not supported');
    }
  }

  // 播放/暂停
  if (musicPlayBtn) {
    musicPlayBtn.addEventListener('click', () => {
      if (!audioCtx) initAudioAnalyser();
      if (audioCtx && audioCtx.state === 'suspended') {
        audioCtx.resume();
      }
      if (bgMusic.paused) {
        bgMusic.play().then(() => {
          musicPlayer.classList.add('playing');
          musicToggle.classList.add('playing');
          musicVisualActive = true;
        }).catch(err => {
          console.warn('播放失败:', err);
        });
      } else {
        bgMusic.pause();
        musicPlayer.classList.remove('playing');
        musicToggle.classList.remove('playing');
        musicVisualActive = false;
      }
    });
  }

  // 格式化时间
  function formatTime(seconds) {
    const m = Math.floor(seconds / 60);
    const s = Math.floor(seconds % 60);
    return m + ':' + (s < 10 ? '0' + s : s);
  }

  // 元数据加载完成 + 主动预加载
  if (bgMusic) {
    // 页面加载后主动开始缓冲音频，减少首次播放延迟
    try { bgMusic.load(); } catch(e) {}

    bgMusic.addEventListener('loadedmetadata', () => {
      if (musicDuration) musicDuration.textContent = formatTime(bgMusic.duration);
    });

    // 进度更新
    bgMusic.addEventListener('timeupdate', () => {
      const pct = (bgMusic.currentTime / bgMusic.duration) * 100;
      if (musicProgressBar) musicProgressBar.style.width = pct + '%';
      if (musicProgressThumb) musicProgressThumb.style.left = pct + '%';
      if (musicCurrent) musicCurrent.textContent = formatTime(bgMusic.currentTime);
    });

    // 结束时重置
    bgMusic.addEventListener('ended', () => {
      musicPlayer.classList.remove('playing');
      musicToggle.classList.remove('playing');
      musicVisualActive = false;
    });
  }

  // 进度条点击跳转
  if (musicProgress) {
    musicProgress.addEventListener('click', (e) => {
      const rect = musicProgress.getBoundingClientRect();
      const pct = (e.clientX - rect.left) / rect.width;
      if (bgMusic.duration) {
        bgMusic.currentTime = pct * bgMusic.duration;
      }
    });
  }

  // 音量控制
  if (bgMusic) bgMusic.volume = 0.7;

  if (volumeSlider) {
    volumeSlider.addEventListener('click', (e) => {
      const rect = volumeSlider.getBoundingClientRect();
      const pct = Math.max(0, Math.min(1, (e.clientX - rect.left) / rect.width));
      if (bgMusic) bgMusic.volume = pct;
      if (volumeBar) volumeBar.style.width = (pct * 100) + '%';
    });
  }

  // 获取音乐频率数据，返回低频到中频的平均能量 (0-1)
  function getMusicEnergy() {
    if (!musicVisualActive || !analyser || !dataArray) return 0;
    analyser.getByteFrequencyData(dataArray);
    // 取低频到中低频（前 1/3）作为节拍能量
    let sum = 0;
    const bassEnd = Math.floor(bufferLength * 0.35);
    for (let i = 0; i < bassEnd; i++) {
      sum += dataArray[i];
    }
    return sum / bassEnd / 255; // 0-1
  }

  // 让网格随音乐跳动：修改 drawGrid 中每块砖的翻转/缩放
  // 在 drawGrid 里调用：如果 musicVisualActive，根据频率给 tile 增加跳动效果
  const originalDrawGrid = drawGrid;
  function enhancedDrawGrid() {
    const W = window.innerWidth;
    const H = window.innerHeight;
    gridCtx.clearRect(0, 0, W, H);

    const fromColor = themeColors[currentThemeIdx]?.grid || 'rgba(109, 40, 217, 0.07)';
    const toColor = themeColors[nextThemeIdx]?.grid || 'rgba(109, 40, 217, 0.07)';

    // 获取音乐能量
    const energy = getMusicEnergy();
    const bassBoost = energy * 0.6; // 音乐越响，跳动越强（调小幅度）

    for (let r = 0; r < gridRows; r++) {
      for (let c = 0; c < gridCols; c++) {
        const x = c * TILE_SIZE;
        const y = r * TILE_SIZE;
        const tile = tiles[r][c];
        const p = tile.flipProgress;

        // 音乐跳动：根据每块砖的位置和当前频率，计算额外的"弹跳"幅度
        // 越靠近底部的砖，对低频越敏感
        const rowFactor = 1 - (r / gridRows); // 底部=1，顶部=0
        let musicPulse = 0;

        if (musicVisualActive && dataArray) {
          // 不同列对应不同频率带
          const freqIndex = Math.floor((c / gridCols) * bufferLength * 0.6);
          const freqValue = dataArray[Math.min(freqIndex, bufferLength - 1)] / 255;
          // 底部行对低频更敏感（整体幅度调小）
          musicPulse = freqValue * rowFactor * bassBoost * 0.25;
        }

        // 合并翻砖进度和音乐跳动
        const totalP = Math.min(1, p + musicPulse * 0.15);
        let scaleX = 1;
        let scaleY = 1;
        let color;

        if (totalP < 0.5) {
          scaleX = 1 - totalP * 1.2;
          scaleY = 1 + musicPulse * 0.12;
          color = fromColor;
        } else {
          scaleX = (totalP - 0.5) * 1.2 + 0.4;
          scaleY = 1 + musicPulse * 0.12;
          color = toColor;
        }

        scaleX = Math.max(0.2, Math.min(1.05, scaleX));
        scaleY = Math.max(0.95, Math.min(1.15, scaleY));

        const drawW = TILE_SIZE * scaleX;
        const drawH = TILE_SIZE * scaleY;
        const drawX = x + (TILE_SIZE - drawW) / 2;
        const drawY = y + (TILE_SIZE - drawH) / 2;

        // 音乐模式下增加发光效果（调小幅度）
        if (musicVisualActive && musicPulse > 0.04) {
          gridCtx.shadowColor = themeColors[currentThemeIdx]?.accent || '#8b5cf6';
          gridCtx.shadowBlur = musicPulse * 5;
        } else {
          gridCtx.shadowBlur = 0;
        }

        if (totalP > 0 && totalP < 1) {
          const alphaMatch = color.match(/[\d.]+\)$/);
          const baseAlpha = parseFloat(alphaMatch?.[0] || 0.07);
          const fillAlpha = Math.min(0.2, baseAlpha * 2 + musicPulse * 0.06);
          gridCtx.fillStyle = color.replace(/[\d.]+\)$/, fillAlpha.toFixed(3) + ')');
          gridCtx.fillRect(drawX + 0.5, drawY + 0.5, drawW - 1, drawH - 1);
        }

        gridCtx.strokeStyle = color;
        gridCtx.lineWidth = 0.3;
        gridCtx.strokeRect(drawX + 0.15, drawY + 0.15, drawW - 0.3, drawH - 0.3);
      }
    }

    gridCtx.shadowBlur = 0;
    requestAnimationFrame(enhancedDrawGrid);
  }

  // 替换 drawGrid
  if (typeof drawGrid === 'function') {
    // 取消原有的 requestAnimationFrame
    // 用新的增强版替代
    window.drawGrid = enhancedDrawGrid;
    requestAnimationFrame(enhancedDrawGrid);
  }

  // ==========================================
  // 19. 咕咕嘎嘎小企鹅
  // ==========================================
  const gugu = document.getElementById('guguGaga');
  const guguSprite = document.getElementById('guguSprite');
  const guguCanvas = document.getElementById('guguCanvas');
  const guguBubble = document.getElementById('guguBubble');
  const guguBubbleText = guguBubble?.querySelector('.gugu-bubble-text');

  if (gugu && guguCanvas && guguSprite) {
    const gCtx = guguCanvas.getContext('2d');
    const CANVAS_W = guguCanvas.width;
    const CANVAS_H = guguCanvas.height;

    // 咕咕嘎嘎语录
    const guguQuotes = [
      '咕呱~', '咕咕嘎嘎！', '咕咕~咕呱~', '嘎嘎咕！',
      '咕...咕...', '嘎嘎嘎~', '咕咕咕！', '呱~',
      '咕咕嘎嘎咕咕~', '咕呱咕呱！',
    ];

    // ========== 加载并抠图 ==========
    const poseList = ['idle', 'walk1', 'walk2', 'jump', 'wave'];
    const poseData = {};
    let loadedCount = 0;

    function removeWhiteBackground(img) {
      const c = document.createElement('canvas');
      c.width = img.naturalWidth;
      c.height = img.naturalHeight;
      const ctx = c.getContext('2d');
      ctx.drawImage(img, 0, 0);

      const imageData = ctx.getImageData(0, 0, c.width, c.height);
      const data = imageData.data;

      for (let i = 0; i < data.length; i += 4) {
        const r = data[i];
        const g = data[i + 1];
        const b = data[i + 2];
        if (r > 235 && g > 235 && b > 235) {
          const minVal = Math.min(r, g, b);
          const alpha = Math.max(0, (255 - minVal) / 20);
          data[i + 3] = Math.floor(data[i + 3] * alpha);
        }
      }

      ctx.putImageData(imageData, 0, 0);

      // 自动裁剪透明边缘
      const w = c.width, h = c.height;
      const d = ctx.getImageData(0, 0, w, h).data;
      let minX = w, minY = h, maxX = 0, maxY = 0;
      let found = false;
      for (let y = 0; y < h; y += 2) {
        for (let x = 0; x < w; x += 2) {
          if (d[(y * w + x) * 4 + 3] > 30) {
            if (x < minX) minX = x;
            if (y < minY) minY = y;
            if (x > maxX) maxX = x;
            if (y > maxY) maxY = y;
            found = true;
          }
        }
      }
      if (!found) return c;

      const pad = 12;
      minX = Math.max(0, minX - pad);
      minY = Math.max(0, minY - pad);
      maxX = Math.min(w, maxX + pad);
      maxY = Math.min(h, maxY + pad);

      const out = document.createElement('canvas');
      out.width = maxX - minX;
      out.height = maxY - minY;
      out.getContext('2d').drawImage(c, minX, minY, out.width, out.height, 0, 0, out.width, out.height);
      return out;
    }

    poseList.forEach(pose => {
      const img = new Image();
      img.crossOrigin = 'anonymous';
      img.onload = () => {
        poseData[pose] = removeWhiteBackground(img);
        loadedCount++;
      };
      img.src = 'assets/gugu/' + pose + '.jpg';
    });

    // ========== 渲染系统 ==========
    let currentPose = 'idle';
    let targetPose = 'idle';
    let crossfadeAlpha = 1;
    const CROSSFADE_SPEED = 0.1;

    let animTime = 0;
    let walkPhase = 0;
    let isJumping = false;
    let jumpProgress = 0;

    function drawGugu() {
      gCtx.clearRect(0, 0, CANVAS_W, CANVAS_H);

      if (loadedCount < poseList.length) {
        requestAnimationFrame(drawGugu);
        return;
      }

      animTime += 0.016;

      // 跳跃动画
      let jumpY = 0, jumpSX = 1, jumpSY = 1;
      if (isJumping) {
        jumpProgress += 0.035;
        if (jumpProgress >= 1) {
          jumpProgress = 0;
          isJumping = false;
          gugu.classList.remove('jumping');
        } else {
          const t = jumpProgress;
          jumpY = -Math.sin(t * Math.PI) * 65;
          if (t < 0.3) {
            jumpSX = 1 + (0.3 - t) * 0.5;
            jumpSY = 1 - (0.3 - t) * 0.25;
          } else if (t > 0.7) {
            jumpSX = 1 + (t - 0.7) * 0.5;
            jumpSY = 1 - (t - 0.7) * 0.25;
          } else {
            jumpSX = 0.95;
            jumpSY = 1.05;
          }
        }
      }

      // 走路摆动
      let walkBob = 0;
      if (!isJumping && (targetPose === 'walk1' || targetPose === 'walk2' || currentPose.startsWith('walk'))) {
        walkPhase += 0.07;
        walkBob = Math.sin(walkPhase) * 3;
      }

      // 呼吸
      const breathe = Math.sin(animTime * 2) * 0.02 + 1;

      const baseX = CANVAS_W / 2;
      const baseY = CANVAS_H - 8 + jumpY + walkBob;

      // 交叉淡入淡出
      if (crossfadeAlpha < 1 && currentPose !== targetPose) {
        crossfadeAlpha += CROSSFADE_SPEED;
        if (crossfadeAlpha >= 1) {
          crossfadeAlpha = 1;
          currentPose = targetPose;
        }
      }

      // 旧帧淡出
      if (crossfadeAlpha < 1 && poseData[currentPose]) {
        drawPose(poseData[currentPose], baseX, baseY, 1 - crossfadeAlpha, breathe, jumpSX, jumpSY);
      }

      // 新帧
      if (poseData[targetPose]) {
        drawPose(poseData[targetPose], baseX, baseY, crossfadeAlpha, breathe, jumpSX, jumpSY);
      }

      requestAnimationFrame(drawGugu);
    }

    function drawPose(canvasImg, x, y, alpha, breathe, sx, sy) {
      const scale = Math.min((CANVAS_W - 30) / canvasImg.width, (CANVAS_H - 40) / canvasImg.height) * 0.95;
      const drawW = canvasImg.width * scale * sx * breathe;
      const drawH = canvasImg.height * scale * sy * breathe;

      gCtx.save();
      gCtx.globalAlpha = alpha;
      gCtx.translate(x, y);
      gCtx.drawImage(canvasImg, -drawW / 2, -drawH, drawW, drawH);
      gCtx.restore();
    }

    function setPose(pose) {
      if (targetPose === pose) return;
      targetPose = pose;
      crossfadeAlpha = 0;
    }

    drawGugu();

    // ========== 对话气泡 ==========
    let bubbleTimer = null;
    function showBubble(text) {
      if (!guguBubbleText || !guguBubble) return;
      guguBubbleText.textContent = text;
      guguBubble.classList.add('show');
      clearTimeout(bubbleTimer);
      bubbleTimer = setTimeout(() => {
        guguBubble.classList.remove('show');
      }, 2000);
    }

    // ========== 走动逻辑 ==========
    let guguX = window.innerWidth / 2;
    let guguDir = 1;
    let guguSpeed = 1.2;
    let isWalking = true;
    let walkFrame = 0;
    let walkFrameCounter = 0;
    const WALK_FRAME_STEPS = 28;

    function updateGugu() {
      if (isWalking && !isJumping) {
        guguX += guguSpeed * guguDir;

        const margin = 100;
        if (guguX > window.innerWidth - margin) {
          guguDir = -1;
          gugu.classList.add('facing-left');
        } else if (guguX < margin) {
          guguDir = 1;
          gugu.classList.remove('facing-left');
        }

        gugu.style.left = guguX + 'px';
        guguSprite.style.transform = '';

        // 走路帧切换
        walkFrameCounter++;
        if (walkFrameCounter >= WALK_FRAME_STEPS) {
          walkFrameCounter = 0;
          walkFrame = 1 - walkFrame;
          setPose(walkFrame === 0 ? 'walk1' : 'walk2');
        }

        // 随机跳跃
        if (Math.random() < 0.0012) {
          guguJump();
        }

        // 随机说话
        if (Math.random() < 0.002) {
          const quote = guguQuotes[Math.floor(Math.random() * guguQuotes.length)];
          showBubble(quote);
        }
      }

      // 跳跃时控制 sprite 的 transform
      if (isJumping) {
        const facingLeft = gugu.classList.contains('facing-left');
        const flip = facingLeft ? -1 : 1;
        const t = jumpProgress;
        const jy = Math.sin(t * Math.PI) * 65;
        let sx = 1, sy = 1;
        if (t < 0.3) { sx = 1 + (0.3 - t) * 0.5; sy = 1 - (0.3 - t) * 0.25; }
        else if (t > 0.7) { sx = 1 + (t - 0.7) * 0.5; sy = 1 - (t - 0.7) * 0.25; }
        else { sx = 0.95; sy = 1.05; }
        guguSprite.style.transform = `translateY(${-jy}px) scale(${sx * flip}, ${sy})`;
      }

      requestAnimationFrame(updateGugu);
    }

    // ========== 跳跃 ==========
    function guguJump() {
      if (isJumping || loadedCount < poseList.length) return;
      isJumping = true;
      jumpProgress = 0;
      setPose('jump');
      gugu.classList.add('jumping');
    }

    // ========== 点击互动 ==========
    gugu.addEventListener('click', () => {
      if (loadedCount < poseList.length) return;
      const reaction = Math.random();

      if (reaction < 0.4) {
        guguJump();
        setTimeout(() => {
          const quote = guguQuotes[Math.floor(Math.random() * guguQuotes.length)];
          showBubble(quote);
        }, 200);
      } else if (reaction < 0.7) {
        const quote = guguQuotes[Math.floor(Math.random() * guguQuotes.length)];
        showBubble(quote);
      } else if (reaction < 0.85) {
        // 挥手
        setPose('wave');
        showBubble('咕咕~');
        setTimeout(() => {
          walkFrame = 0;
          walkFrameCounter = 0;
          setPose('walk1');
        }, 1200);
      } else {
        // 转身
        guguDir *= -1;
        gugu.classList.toggle('facing-left');
        showBubble('咕~');
      }
    });

    gugu.addEventListener('mouseenter', () => {
      if (!isJumping && loadedCount >= poseList.length) {
        showBubble('咕呱？');
      }
    });

    window.addEventListener('resize', () => {
      const margin = 100;
      if (guguX > window.innerWidth - margin) guguX = window.innerWidth - margin;
      if (guguX < margin) guguX = margin;
    });

    // 启动
    setTimeout(() => {
      gugu.classList.add('walking');
      setPose('walk1');
      updateGugu();
    }, 1000);
  }


});
